; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Start
StartDisarkGenerateExternalLabel

DisarkByteRegionStart0
	db "AT20"
DisarkPointerRegionStart1
	dw ArpeggioTable	; The address of the Arpeggio table.
	dw PitchTable	; The address of the Pitch table.
	dw InstrumentTable	; The address of the Instrument table.
	dw EffectBlockTable	; The address of the Effect Block table.
DisarkPointerRegionEnd1


; The addresses of each Subsong:
DisarkPointerRegionStart2
	dw Subsong0_Start
DisarkPointerRegionEnd2

; Declares all the Arpeggios.
ArpeggioTable
DisarkPointerRegionStart3
DisarkPointerRegionEnd3

; Declares all the Pitches.
PitchTable
DisarkPointerRegionStart4
DisarkPointerRegionEnd4

; Declares all the Instruments.
InstrumentTable
DisarkPointerRegionStart5
	dw EmptyInstrument
	dw Instrument1
	dw Instrument2
	dw Instrument3
	dw Instrument4
	dw Instrument5
	dw Instrument6
DisarkPointerRegionEnd5

EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 78	; Additional data. Noise: 14. Pitch? false. Arp? true. Period? false.
	db 5	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 70	; Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 249	; Soft only. Volume: 15. Volume only.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -5	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -10	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -10	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -15	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -15	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -15	; Arpeggio.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -15	; Arpeggio.

	db 73	; Soft only. Volume: 9.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -15	; Arpeggio.

	db 169	; Soft only. Volume: 5. Volume only.

	db 6	; Loop to silence.

Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 105	; Additional data. Noise: 9. Pitch? true. Arp? true. Period? false.
	db 126	; Arpeggio.
	dw -5	; Pitch.

	db 121	; Soft only. Volume: 15.
	db 71	; Additional data. Noise: 7. Pitch? false. Arp? true. Period? false.
	db 82	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 70	; Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
	db 124	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 69	; Additional data. Noise: 5. Pitch? false. Arp? true. Period? false.
	db 85	; Arpeggio.

	db 113	; Soft only. Volume: 14.
	db 4	; Additional data. Noise: 4. Pitch? false. Arp? false. Period? false.

	db 97	; Soft only. Volume: 12.
	db 3	; Additional data. Noise: 3. Pitch? false. Arp? false. Period? false.

	db 81	; Soft only. Volume: 10.
	db 2	; Additional data. Noise: 2. Pitch? false. Arp? false. Period? false.

	db 65	; Soft only. Volume: 8.
	db 1	; Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

	db 177	; Soft only. Volume: 6. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 6	; Loop to silence.

Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 224	; No Soft no Hard. Volume: 12. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

Instrument4
	db 1	; The speed (>0, 0 for 256).
	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 1	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 1	; Arpeggio.

	db 209	; Soft only. Volume: 10. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 6	; Loop to silence.

Instrument5
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 3	; Additional data. Noise: 3. Pitch? false. Arp? false. Period? false.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 6	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 4	; Arpeggio.

	db 249	; Soft only. Volume: 15. Volume only.

	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 6	; Arpeggio.

	db 225	; Soft only. Volume: 12. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 6	; Loop to silence.

Instrument6
	db 1	; The speed (>0, 0 for 256).
Instrument6_Loop	db 249	; Soft only. Volume: 15. Volume only.

	db 7	; Loop.
DisarkWordForceReference6
	dw Instrument6_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
EffectBlockTable
DisarkPointerRegionStart7
	dw EffectBlock_P4P0	; Index 0
	dw EffectBlock_P4P3	; Index 1
	dw EffectBlock_P4P5	; Index 2
	dw EffectBlock_P4P9	; Index 3
DisarkPointerRegionEnd7

EffectBlock_P4P0
	db 4, 0
EffectBlock_P4P3
	db 4, 3
EffectBlock_P4P5
	db 4, 5
EffectBlock_P4P9
	db 4, 9

DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Subsong0_DisarkByteRegionStart0
Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 20	; Loop start index (>=0).
	db 35	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 10	; Base note index (>=0).

Subsong0_Linker
Subsong0_DisarkPointerRegionStart1
; Position 0
	dw Subsong0_Track0
	dw Subsong0_Track13
	dw Subsong0_Track0
	dw Subsong0_LinkerBlock0

; Position 1
	dw Subsong0_Track12
	dw Subsong0_Track14
	dw Subsong0_Track15
	dw Subsong0_LinkerBlock1

; Position 2
	dw Subsong0_Track12
	dw Subsong0_Track14
	dw Subsong0_Track15
	dw Subsong0_LinkerBlock1

; Position 3
	dw Subsong0_Track12
	dw Subsong0_Track19
	dw Subsong0_Track20
	dw Subsong0_LinkerBlock1

; Position 4
	dw Subsong0_Track12
	dw Subsong0_Track19
	dw Subsong0_Track20
	dw Subsong0_LinkerBlock1

; Position 5
	dw Subsong0_Track12
	dw Subsong0_Track14
	dw Subsong0_Track15
	dw Subsong0_LinkerBlock1

; Position 6
	dw Subsong0_Track12
	dw Subsong0_Track14
	dw Subsong0_Track15
	dw Subsong0_LinkerBlock1

; Position 7
	dw Subsong0_Track12
	dw Subsong0_Track19
	dw Subsong0_Track20
	dw Subsong0_LinkerBlock2

; Position 8
	dw Subsong0_Track16
	dw Subsong0_Track17
	dw Subsong0_Track18
	dw Subsong0_LinkerBlock3

; Position 9
	dw Subsong0_Track0
	dw Subsong0_Track4
	dw Subsong0_Track0
	dw Subsong0_LinkerBlock1

; Position 10
	dw Subsong0_Track0
	dw Subsong0_Track5
	dw Subsong0_Track0
	dw Subsong0_LinkerBlock4

; Position 11
	dw Subsong0_Track0
	dw Subsong0_Track5
	dw Subsong0_Track0
	dw Subsong0_LinkerBlock4

; Position 12
	dw Subsong0_Track10
	dw Subsong0_Track5
	dw Subsong0_Track3
	dw Subsong0_LinkerBlock4

; Position 13
	dw Subsong0_Track11
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 14
	dw Subsong0_Track1
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 15
	dw Subsong0_Track1
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 16
	dw Subsong0_Track2
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 17
	dw Subsong0_Track7
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 18
	dw Subsong0_Track8
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 19
	dw Subsong0_Track8
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 20
Subsong0_Linker_Loop
	dw Subsong0_Track9
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 21
	dw Subsong0_Track9
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 22
	dw Subsong0_Track1
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 23
	dw Subsong0_Track1
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 24
	dw Subsong0_Track2
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 25
	dw Subsong0_Track7
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 26
	dw Subsong0_Track8
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 27
	dw Subsong0_Track8
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 28
	dw Subsong0_Track9
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 29
	dw Subsong0_Track9
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 30
	dw Subsong0_Track1
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 31
	dw Subsong0_Track1
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 32
	dw Subsong0_Track2
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 33
	dw Subsong0_Track7
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 34
	dw Subsong0_Track8
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

; Position 35
	dw Subsong0_Track8
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_LinkerBlock4

Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
Subsong0_DisarkWordForceReference2
	dw Subsong0_Linker_Loop

Subsong0_LinkerBlock0
	db 8	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference3
	dw Subsong0_SpeedTrack0	; SpeedTrack address.
Subsong0_DisarkWordForceReference4
	dw Subsong0_EventTrack0	; EventTrack address.
Subsong0_LinkerBlock1
	db 24	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference5
	dw Subsong0_SpeedTrack0	; SpeedTrack address.
Subsong0_DisarkWordForceReference6
	dw Subsong0_EventTrack0	; EventTrack address.
Subsong0_LinkerBlock2
	db 12	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference7
	dw Subsong0_SpeedTrack0	; SpeedTrack address.
Subsong0_DisarkWordForceReference8
	dw Subsong0_EventTrack0	; EventTrack address.
Subsong0_LinkerBlock3
	db 17	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference9
	dw Subsong0_SpeedTrack0	; SpeedTrack address.
Subsong0_DisarkWordForceReference10
	dw Subsong0_EventTrack0	; EventTrack address.
Subsong0_LinkerBlock4
	db 32	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference11
	dw Subsong0_SpeedTrack0	; SpeedTrack address.
Subsong0_DisarkWordForceReference12
	dw Subsong0_EventTrack0	; EventTrack address.

Subsong0_Track0
	db 61, 127	; Waits for 128 lines.


Subsong0_Track1
	db 226
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 35
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 35
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 34
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 34
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 35
	db 35
	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track2
	db 163
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 34
	db 35
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 35
	db 60	; Waits for 1 line.

	db 36
	db 35
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 35
	db 60	; Waits for 1 line.

	db 34
	db 35
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 35
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 34
	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track3
	db 61, 23	; Waits for 24 lines.

	db 130
	db 2	; New Instrument (2).
	db 2
	db 60	; Waits for 1 line.

	db 2
	db 2
	db 60	; Waits for 1 line.

	db 2
	db 61, 127	; Waits for 128 lines.


Subsong0_Track4
	db 130
	db 6	; New Instrument (6).
	db 61, 6	; Waits for 7 lines.

	db 4
	db 61, 6	; Waits for 7 lines.

	db 6
	db 61, 127	; Waits for 128 lines.


Subsong0_Track5
	db 132
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 4
	db 60	; Waits for 1 line.

	db 4
	db 6
	db 4
	db 2
	db 4
	db 6
	db 4
	db 61, 127	; Waits for 128 lines.


Subsong0_Track6
	db 148
	db 1	; New Instrument (1).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 2	; New Instrument (2).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 1	; New Instrument (1).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 2	; New Instrument (2).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 1	; New Instrument (1).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 2	; New Instrument (2).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 1	; New Instrument (1).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 2	; New Instrument (2).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 1	; New Instrument (1).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 2	; New Instrument (2).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 1	; New Instrument (1).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 2	; New Instrument (2).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 1	; New Instrument (1).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 2	; New Instrument (2).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 1	; New Instrument (1).
	db 130
	db 3	; New Instrument (3).
	db 148
	db 1	; New Instrument (1).
	db 2
	db 61, 127	; Waits for 128 lines.


Subsong0_Track7
	db 163
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 34
	db 35
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 35
	db 60	; Waits for 1 line.

	db 36
	db 35
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 35
	db 60	; Waits for 1 line.

	db 34
	db 35
	db 60	; Waits for 1 line.

	db 33
	db 33
	db 34
	db 35
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 33
	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track8
	db 163
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 34
	db 35
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 35
	db 60	; Waits for 1 line.

	db 36
	db 35
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 33
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 34
	db 35
	db 60	; Waits for 1 line.

	db 33
	db 33
	db 34
	db 35
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 33
	db 35
	db 60	; Waits for 1 line.

	db 33
	db 61, 127	; Waits for 128 lines.


Subsong0_Track9
	db 160
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 32
	db 32
	db 32
	db 60	; Waits for 1 line.

	db 30
	db 28
	db 27
	db 60	; Waits for 1 line.

	db 27
	db 27
	db 27
	db 60	; Waits for 1 line.

	db 30
	db 31
	db 33
	db 60	; Waits for 1 line.

	db 33
	db 33
	db 33
	db 60	; Waits for 1 line.

	db 30
	db 30
	db 32
	db 60	; Waits for 1 line.

	db 32
	db 32
	db 32
	db 61, 127	; Waits for 128 lines.


Subsong0_Track10
	db 227
	db 5	; New Instrument (5).
	db 3	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 99
	db 2	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 99
	db 1	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track11
	db 227
	db 5	; New Instrument (5).
	db 0	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 35
	db 61, 6	; Waits for 7 lines.

	db 35
	db 61, 6	; Waits for 7 lines.

	db 35
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 35
	db 33
	db 35
	db 61, 127	; Waits for 128 lines.


Subsong0_Track12
	db 183
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 55
	db 60	; Waits for 1 line.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 61, 127	; Waits for 128 lines.


Subsong0_Track13
	db 191
	db 71	; Escape note (71).
	db 4	; New Instrument (4).
	db 63
	db 72	; Escape note (72).
	db 63
	db 74	; Escape note (74).
	db 63
	db 76	; Escape note (76).
	db 63
	db 77	; Escape note (77).
	db 63
	db 79	; Escape note (79).
	db 63
	db 81	; Escape note (81).
	db 63
	db 83	; Escape note (83).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track14
	db 178
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 50
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 49
	db 60	; Waits for 1 line.

	db 63
	db 72	; Escape note (72).
	db 63
	db 74	; Escape note (74).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 49
	db 60	; Waits for 1 line.

	db 49
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 47
	db 60	; Waits for 1 line.

	db 63
	db 74	; Escape note (74).
	db 63
	db 69	; Escape note (69).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track15
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 178
	db 5	; New Instrument (5).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 158
	db 2	; New Instrument (2).
	db 178
	db 5	; New Instrument (5).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 158
	db 2	; New Instrument (2).
	db 178
	db 5	; New Instrument (5).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track16
	db 178
	db 4	; New Instrument (4).
	db 47
	db 47
	db 43
	db 47
	db 31
	db 35
	db 28
	db 31
	db 33
	db 21
	db 24
	db 21
	db 19
	db 18
	db 16
	db 150
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track17
	db 61, 13	; Waits for 14 lines.

	db 163
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track18
	db 178
	db 5	; New Instrument (5).
	db 47
	db 49
	db 43
	db 45
	db 40
	db 43
	db 37
	db 38
	db 33
	db 35
	db 28
	db 26
	db 23
	db 19
	db 150
	db 1	; New Instrument (1).
	db 61, 127	; Waits for 128 lines.


Subsong0_Track19
	db 174
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 46
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 45
	db 60	; Waits for 1 line.

	db 63
	db 68	; Escape note (68).
	db 63
	db 70	; Escape note (70).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 45
	db 60	; Waits for 1 line.

	db 45
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 41
	db 43
	db 60	; Waits for 1 line.

	db 63
	db 70	; Escape note (70).
	db 55
	db 61, 127	; Waits for 128 lines.


Subsong0_Track20
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 177
	db 5	; New Instrument (5).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 157
	db 2	; New Instrument (2).
	db 177
	db 5	; New Instrument (5).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 49
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 156
	db 2	; New Instrument (2).
	db 176
	db 5	; New Instrument (5).
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

Subsong0_DisarkByteRegionEnd0
