# Untitled, AKG format, v1.0.

# Generated by Arkos Tracker 2.

.list
Start:
StartDisarkGenerateExternalLabel:

DisarkByteRegionStart0:
    .ascii "AT20"
DisarkPointerRegionStart1:
    .word ArpeggioTable    # The address of the Arpeggio table.
    .word PitchTable       # The address of the Pitch table.
    .word InstrumentTable  # The address of the Instrument table.
    .word EffectBlockTable # The address of the Effect Block table.
DisarkPointerRegionEnd1:


# The addresses of each Subsong:
DisarkPointerRegionStart2:
    .word Subsong0_Start
DisarkPointerRegionEnd2:

# Declares all the Arpeggios.
ArpeggioTable:
DisarkPointerRegionStart3:
DisarkPointerRegionEnd3:

# Declares all the Pitches.
PitchTable:
DisarkPointerRegionStart4:
DisarkPointerRegionEnd4:

# Declares all the Instruments.
InstrumentTable:
DisarkPointerRegionStart5:
    .word EmptyInstrument
    .word Instrument1
    .word Instrument2
    .word Instrument3
    .word Instrument4
    .word Instrument5
    .word Instrument6
DisarkPointerRegionEnd5:

EmptyInstrument:
    .byte 0    # The speed (>0, 0 for 256).
EmptyInstrument_Loop:
    .byte 0    # No Soft no Hard. Volume: 0. Noise? false.

    .byte 6    # Loop to silence.

.nolist

Instrument1:
    .byte 1    # The speed (>0, 0 for 256).
    .byte 121  # Soft only. Volume: 15.
    .byte 78   # Additional data. Noise: 14. Pitch? false. Arp? true. Period? false.
    .byte 5    # Arpeggio.

    .byte 121  # Soft only. Volume: 15.
    .byte 70   # Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
    .byte 3    # Arpeggio.

    .byte 249  # Soft only. Volume: 15. Volume only.

    .byte 121  # Soft only. Volume: 15.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte -5   # Arpeggio.

    .byte 113  # Soft only. Volume: 14.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte -10  # Arpeggio.

    .byte 113  # Soft only. Volume: 14.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte -10  # Arpeggio.

    .byte 97   # Soft only. Volume: 12.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte -15  # Arpeggio.

    .byte 97   # Soft only. Volume: 12.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte -15  # Arpeggio.

    .byte 97   # Soft only. Volume: 12.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte -15  # Arpeggio.

    .byte 89   # Soft only. Volume: 11.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte -15  # Arpeggio.

    .byte 73   # Soft only. Volume: 9.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte -15  # Arpeggio.

    .byte 169  # Soft only. Volume: 5. Volume only.

    .byte 6    # Loop to silence.

Instrument2:
    .byte 1    # The speed (>0, 0 for 256).
    .byte 121  # Soft only. Volume: 15.
    .byte 105  # Additional data. Noise: 9. Pitch? true. Arp? true. Period? false.
    .byte 126  # Arpeggio.
    .word -5   # Pitch.

    .byte 121  # Soft only. Volume: 15.
    .byte 71   # Additional data. Noise: 7. Pitch? false. Arp? true. Period? false.
    .byte 82   # Arpeggio.

    .byte 121  # Soft only. Volume: 15.
    .byte 70   # Additional data. Noise: 6. Pitch? false. Arp? true. Period? false.
    .byte 124  # Arpeggio.

    .byte 121  # Soft only. Volume: 15.
    .byte 69   # Additional data. Noise: 5. Pitch? false. Arp? true. Period? false.
    .byte 85   # Arpeggio.

    .byte 113  # Soft only. Volume: 14.
    .byte 4    # Additional data. Noise: 4. Pitch? false. Arp? false. Period? false.

    .byte 97   # Soft only. Volume: 12.
    .byte 3    # Additional data. Noise: 3. Pitch? false. Arp? false. Period? false.

    .byte 81   # Soft only. Volume: 10.
    .byte 2    # Additional data. Noise: 2. Pitch? false. Arp? false. Period? false.

    .byte 65   # Soft only. Volume: 8.
    .byte 1    # Additional data. Noise: 1. Pitch? false. Arp? false. Period? false.

    .byte 177  # Soft only. Volume: 6. Volume only.

    .byte 177  # Soft only. Volume: 6. Volume only.

    .byte 6    # Loop to silence.

Instrument3:
    .byte 1    # The speed (>0, 0 for 256).
    .byte 224  # No Soft no Hard. Volume: 12. Noise? true.
    .byte 1    # Noise: 1.

    .byte 6    # Loop to silence.

Instrument4:
    .byte 1    # The speed (>0, 0 for 256).
    .byte 105  # Soft only. Volume: 13.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte 1    # Arpeggio.

    .byte 121  # Soft only. Volume: 15.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte 1    # Arpeggio.

    .byte 209  # Soft only. Volume: 10. Volume only.

    .byte 233  # Soft only. Volume: 13. Volume only.

    .byte 225  # Soft only. Volume: 12. Volume only.

    .byte 209  # Soft only. Volume: 10. Volume only.

    .byte 193  # Soft only. Volume: 8. Volume only.

    .byte 177  # Soft only. Volume: 6. Volume only.

    .byte 161  # Soft only. Volume: 4. Volume only.

    .byte 6    # Loop to silence.

Instrument5:
    .byte 1    # The speed (>0, 0 for 256).
    .byte 121  # Soft only. Volume: 15.
    .byte 3    # Additional data. Noise: 3. Pitch? false. Arp? false. Period? false.

    .byte 121  # Soft only. Volume: 15.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte 6    # Arpeggio.

    .byte 121  # Soft only. Volume: 15.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte 4    # Arpeggio.

    .byte 249  # Soft only. Volume: 15. Volume only.

    .byte 121  # Soft only. Volume: 15.
    .byte 64   # Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
    .byte 6    # Arpeggio.

    .byte 225  # Soft only. Volume: 12. Volume only.

    .byte 201  # Soft only. Volume: 9. Volume only.

    .byte 6    # Loop to silence.

Instrument6:
    .byte 1    # The speed (>0, 0 for 256).
Instrument6_Loop:    .byte 249  # Soft only. Volume: 15. Volume only.

    .byte 7    # Loop.
    .list
    .even
DisarkWordForceReference6:
    .word Instrument6_Loop # Loop here.
    .nolist


# The indexes of the effect blocks used by this song.
EffectBlockTable:
DisarkPointerRegionStart7:
    .word EffectBlock_P4P0 # Index 0
    .word EffectBlock_P4P3 # Index 1
    .word EffectBlock_P4P5 # Index 2
    .word EffectBlock_P4P9 # Index 3
DisarkPointerRegionEnd7:

EffectBlock_P4P0:
    .byte 4, 0
EffectBlock_P4P3:
    .byte 4, 3
EffectBlock_P4P5:
    .byte 4, 5
EffectBlock_P4P9:
    .byte 4, 9

DisarkByteRegionEnd0:

# Subsong 0
# ----------------------
Subsong0_DisarkByteRegionStart0:
Subsong0_Start:
    .byte 2    # ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
    .byte 0    # Digichannel (0-2).
    .byte 1    # PSG count (>0).
    .byte 20   # Loop start index (>=0).
    .byte 35   # End index (>=0).
    .byte 6    # Initial speed (>=0).
    .byte 10   # Base note index (>=0).

.list
    .even
Subsong0_Linker:
Subsong0_DisarkPointerRegionStart1:
# Position 0
    .word Subsong0_Track0
.nolist
    .word Subsong0_Track13
    .word Subsong0_Track0
    .word Subsong0_LinkerBlock0

# Position 1
    .word Subsong0_Track12
    .word Subsong0_Track14
    .word Subsong0_Track15
    .word Subsong0_LinkerBlock1

# Position 2
    .word Subsong0_Track12
    .word Subsong0_Track14
    .word Subsong0_Track15
    .word Subsong0_LinkerBlock1

# Position 3
    .word Subsong0_Track12
    .word Subsong0_Track19
    .word Subsong0_Track20
    .word Subsong0_LinkerBlock1

# Position 4
    .word Subsong0_Track12
    .word Subsong0_Track19
    .word Subsong0_Track20
    .word Subsong0_LinkerBlock1

# Position 5
    .word Subsong0_Track12
    .word Subsong0_Track14
    .word Subsong0_Track15
    .word Subsong0_LinkerBlock1

# Position 6
    .word Subsong0_Track12
    .word Subsong0_Track14
    .word Subsong0_Track15
    .word Subsong0_LinkerBlock1

# Position 7
    .word Subsong0_Track12
    .word Subsong0_Track19
    .word Subsong0_Track20
    .word Subsong0_LinkerBlock2

# Position 8
    .word Subsong0_Track16
    .word Subsong0_Track17
    .word Subsong0_Track18
    .word Subsong0_LinkerBlock3

# Position 9
    .word Subsong0_Track0
    .word Subsong0_Track4
    .word Subsong0_Track0
    .word Subsong0_LinkerBlock1

# Position 10
    .word Subsong0_Track0
    .word Subsong0_Track5
    .word Subsong0_Track0
    .word Subsong0_LinkerBlock4

# Position 11
    .word Subsong0_Track0
    .word Subsong0_Track5
    .word Subsong0_Track0
    .word Subsong0_LinkerBlock4

# Position 12
    .word Subsong0_Track10
    .word Subsong0_Track5
    .word Subsong0_Track3
    .word Subsong0_LinkerBlock4

# Position 13
    .word Subsong0_Track11
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 14
    .word Subsong0_Track1
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 15
    .word Subsong0_Track1
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 16
    .word Subsong0_Track2
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 17
    .word Subsong0_Track7
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 18
    .word Subsong0_Track8
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 19
    .word Subsong0_Track8
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 20
Subsong0_Linker_Loop:
    .word Subsong0_Track9
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 21
    .word Subsong0_Track9
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 22
    .word Subsong0_Track1
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 23
    .word Subsong0_Track1
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 24
    .word Subsong0_Track2
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 25
    .word Subsong0_Track7
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 26
    .word Subsong0_Track8
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 27
    .word Subsong0_Track8
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 28
    .word Subsong0_Track9
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 29
    .word Subsong0_Track9
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 30
    .word Subsong0_Track1
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 31
    .word Subsong0_Track1
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 32
    .word Subsong0_Track2
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 33
    .word Subsong0_Track7
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 34
    .word Subsong0_Track8
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

# Position 35
    .word Subsong0_Track8
    .word Subsong0_Track5
    .word Subsong0_Track6
    .word Subsong0_LinkerBlock4

Subsong0_DisarkPointerRegionEnd1:
    .word 0    # Loop.
Subsong0_DisarkWordForceReference2:
    .word Subsong0_Linker_Loop

    .list
Subsong0_LinkerBlock0:
    .byte 8    # Height.
    .byte 0    # Transposition 0.
    .byte 0    # Transposition 1.
    .byte 0    # Transposition 2.
    .nolist
Subsong0_DisarkWordForceReference3:
    .word Subsong0_SpeedTrack0 # SpeedTrack address.
Subsong0_DisarkWordForceReference4:
    .word Subsong0_EventTrack0 # EventTrack address.
Subsong0_LinkerBlock1:
    .byte 24   # Height.
    .byte 0    # Transposition 0.
    .byte 0    # Transposition 1.
    .byte 0    # Transposition 2.
Subsong0_DisarkWordForceReference5:
    .word Subsong0_SpeedTrack0 # SpeedTrack address.
Subsong0_DisarkWordForceReference6:
    .word Subsong0_EventTrack0 # EventTrack address.
Subsong0_LinkerBlock2:
    .byte 12   # Height.
    .byte 0    # Transposition 0.
    .byte 0    # Transposition 1.
    .byte 0    # Transposition 2.
Subsong0_DisarkWordForceReference7:
    .word Subsong0_SpeedTrack0 # SpeedTrack address.
Subsong0_DisarkWordForceReference8:
    .word Subsong0_EventTrack0 # EventTrack address.
Subsong0_LinkerBlock3:
    .byte 17   # Height.
    .byte 0    # Transposition 0.
    .byte 0    # Transposition 1.
    .byte 0    # Transposition 2.
Subsong0_DisarkWordForceReference9:
    .word Subsong0_SpeedTrack0 # SpeedTrack address.
Subsong0_DisarkWordForceReference10:
    .word Subsong0_EventTrack0 # EventTrack address.
Subsong0_LinkerBlock4:
    .byte 32   # Height.
    .byte 0    # Transposition 0.
    .byte 0    # Transposition 1.
    .byte 0    # Transposition 2.
Subsong0_DisarkWordForceReference11:
    .word Subsong0_SpeedTrack0 # SpeedTrack address.
Subsong0_DisarkWordForceReference12:
    .word Subsong0_EventTrack0 # EventTrack address.

.list
Subsong0_Track0:
    .byte 61, 127  # Waits for 128 lines.
.nolist


Subsong0_Track1:
    .byte 226
    .byte 5    # New Instrument (5).
    .byte 0    # Index to an effect block.
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 34
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 35
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 35
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 34
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 34
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 35
    .byte 35
    .byte 35
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track2:
    .byte 163
    .byte 5    # New Instrument (5).
    .byte 60   # Waits for 1 line.

    .byte 34
    .byte 35
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 36
    .byte 35
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 34
    .byte 35
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 34
    .byte 60   # Waits for 1 line.

    .byte 34
    .byte 35
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track3:
    .byte 61, 23   # Waits for 24 lines.

    .byte 130
    .byte 2    # New Instrument (2).
    .byte 2
    .byte 60   # Waits for 1 line.

    .byte 2
    .byte 2
    .byte 60   # Waits for 1 line.

    .byte 2
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track4:
    .byte 130
    .byte 6    # New Instrument (6).
    .byte 61, 6    # Waits for 7 lines.

    .byte 4
    .byte 61, 6    # Waits for 7 lines.

    .byte 6
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track5:
    .byte 132
    .byte 4    # New Instrument (4).
    .byte 60   # Waits for 1 line.

    .byte 4
    .byte 60   # Waits for 1 line.

    .byte 7
    .byte 60   # Waits for 1 line.

    .byte 4
    .byte 60   # Waits for 1 line.

    .byte 4
    .byte 60   # Waits for 1 line.

    .byte 4
    .byte 60   # Waits for 1 line.

    .byte 9
    .byte 60   # Waits for 1 line.

    .byte 4
    .byte 60   # Waits for 1 line.

    .byte 4
    .byte 60   # Waits for 1 line.

    .byte 4
    .byte 60   # Waits for 1 line.

    .byte 6
    .byte 60   # Waits for 1 line.

    .byte 4
    .byte 60   # Waits for 1 line.

    .byte 4
    .byte 6
    .byte 4
    .byte 2
    .byte 4
    .byte 6
    .byte 4
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track6:
    .byte 148
    .byte 1    # New Instrument (1).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 2    # New Instrument (2).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 1    # New Instrument (1).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 2    # New Instrument (2).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 1    # New Instrument (1).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 2    # New Instrument (2).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 1    # New Instrument (1).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 2    # New Instrument (2).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 1    # New Instrument (1).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 2    # New Instrument (2).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 1    # New Instrument (1).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 2    # New Instrument (2).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 1    # New Instrument (1).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 2    # New Instrument (2).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 1    # New Instrument (1).
    .byte 130
    .byte 3    # New Instrument (3).
    .byte 148
    .byte 1    # New Instrument (1).
    .byte 2
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track7:
    .byte 163
    .byte 5    # New Instrument (5).
    .byte 60   # Waits for 1 line.

    .byte 34
    .byte 35
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 36
    .byte 35
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 34
    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 33
    .byte 33
    .byte 34
    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 33
    .byte 60   # Waits for 1 line.

    .byte 33
    .byte 35
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track8:
    .byte 163
    .byte 5    # New Instrument (5).
    .byte 60   # Waits for 1 line.

    .byte 34
    .byte 35
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 36
    .byte 35
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 33
    .byte 60   # Waits for 1 line.

    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 34
    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 33
    .byte 33
    .byte 34
    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 33
    .byte 60   # Waits for 1 line.

    .byte 33
    .byte 35
    .byte 60   # Waits for 1 line.

    .byte 33
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track9:
    .byte 160
    .byte 5    # New Instrument (5).
    .byte 60   # Waits for 1 line.

    .byte 32
    .byte 32
    .byte 32
    .byte 60   # Waits for 1 line.

    .byte 30
    .byte 28
    .byte 27
    .byte 60   # Waits for 1 line.

    .byte 27
    .byte 27
    .byte 27
    .byte 60   # Waits for 1 line.

    .byte 30
    .byte 31
    .byte 33
    .byte 60   # Waits for 1 line.

    .byte 33
    .byte 33
    .byte 33
    .byte 60   # Waits for 1 line.

    .byte 30
    .byte 30
    .byte 32
    .byte 60   # Waits for 1 line.

    .byte 32
    .byte 32
    .byte 32
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track10:
    .byte 227
    .byte 5    # New Instrument (5).
    .byte 3    # Index to an effect block.
    .byte 61, 6    # Waits for 7 lines.

    .byte 99
    .byte 2    # Index to an effect block.
    .byte 61, 6    # Waits for 7 lines.

    .byte 99
    .byte 1    # Index to an effect block.
    .byte 61, 6    # Waits for 7 lines.

    .byte 35
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track11:
    .byte 227
    .byte 5    # New Instrument (5).
    .byte 0    # Index to an effect block.
    .byte 61, 6    # Waits for 7 lines.

    .byte 35
    .byte 61, 6    # Waits for 7 lines.

    .byte 35
    .byte 61, 6    # Waits for 7 lines.

    .byte 35
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 35
    .byte 33
    .byte 35
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track12:
    .byte 183
    .byte 3    # New Instrument (3).
    .byte 60   # Waits for 1 line.

    .byte 55
    .byte 62 + 1 * 64  # Optimized wait for 3 lines.

    .byte 31
    .byte 62 + 3 * 64  # Optimized wait for 5 lines.

    .byte 55
    .byte 60   # Waits for 1 line.

    .byte 55
    .byte 62 + 1 * 64  # Optimized wait for 3 lines.

    .byte 31
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track13:
    .byte 191  # 128 + 63
    .byte 71   # Escape note (71).
    .byte 4    # New Instrument (4).
# -----------
    .byte 63
    .byte 72   # Escape note (72).
    .byte 63
    .byte 74   # Escape note (74).
    .byte 63
    .byte 76   # Escape note (76).
    .byte 63
    .byte 77   # Escape note (77).
    .byte 63
    .byte 79   # Escape note (79).
    .byte 63
    .byte 81   # Escape note (81).
    .byte 63
    .byte 83   # Escape note (83).
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track14:
    .byte 178
    .byte 4    # New Instrument (4).
    .byte 60   # Waits for 1 line.

    .byte 50
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 47
    .byte 49
    .byte 60   # Waits for 1 line.

    .byte 63
    .byte 72   # Escape note (72).
    .byte 63
    .byte 74   # Escape note (74).
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 49
    .byte 60   # Waits for 1 line.

    .byte 49
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 45
    .byte 47
    .byte 60   # Waits for 1 line.

    .byte 63
    .byte 74   # Escape note (74).
    .byte 63
    .byte 69   # Escape note (69).
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track15:
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 178
    .byte 5    # New Instrument (5).
    .byte 62 + 3 * 64  # Optimized wait for 5 lines.

    .byte 158
    .byte 2    # New Instrument (2).
    .byte 178
    .byte 5    # New Instrument (5).
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 50
    .byte 62 + 3 * 64  # Optimized wait for 5 lines.

    .byte 158
    .byte 2    # New Instrument (2).
    .byte 178
    .byte 5    # New Instrument (5).
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track16:
    .byte 178
    .byte 4    # New Instrument (4).
    .byte 47
    .byte 47
    .byte 43
    .byte 47
    .byte 31
    .byte 35
    .byte 28
    .byte 31
    .byte 33
    .byte 21
    .byte 24
    .byte 21
    .byte 19
    .byte 18
    .byte 16
    .byte 150
    .byte 1    # New Instrument (1).
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track17:
    .byte 61, 13   # Waits for 14 lines.

    .byte 163
    .byte 2    # New Instrument (2).
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track18:
    .byte 178
    .byte 5    # New Instrument (5).
    .byte 47
    .byte 49
    .byte 43
    .byte 45
    .byte 40
    .byte 43
    .byte 37
    .byte 38
    .byte 33
    .byte 35
    .byte 28
    .byte 26
    .byte 23
    .byte 19
    .byte 150
    .byte 1    # New Instrument (1).
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track19:
    .byte 174
    .byte 4    # New Instrument (4).
    .byte 60   # Waits for 1 line.

    .byte 46
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 43
    .byte 45
    .byte 60   # Waits for 1 line.

    .byte 63
    .byte 68   # Escape note (68).
    .byte 63
    .byte 70   # Escape note (70).
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 45
    .byte 60   # Waits for 1 line.

    .byte 45
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 41
    .byte 43
    .byte 60   # Waits for 1 line.

    .byte 63
    .byte 70   # Escape note (70).
    .byte 55
    .byte 61, 127  # Waits for 128 lines.


Subsong0_Track20:
    .byte 62 + 0 * 64  # Optimized wait for 2 lines.

    .byte 177
    .byte 5    # New Instrument (5).
    .byte 62 + 3 * 64  # Optimized wait for 5 lines.

    .byte 157
    .byte 2    # New Instrument (2).
    .byte 177
    .byte 5    # New Instrument (5).
    .byte 62 + 2 * 64  # Optimized wait for 4 lines.

    .byte 49
    .byte 62 + 3 * 64  # Optimized wait for 5 lines.

    .byte 156
    .byte 2    # New Instrument (2).
    .byte 176
    .byte 5    # New Instrument (5).
    .byte 61, 127  # Waits for 128 lines.


# The speed tracks
Subsong0_SpeedTrack0:
    .byte 255  # Wait for 128 lines.

# The event tracks
Subsong0_EventTrack0:
    .byte 255  # Wait for 128 lines.

Subsong0_DisarkByteRegionEnd0:
