#New song, AKG format, v1.0.

#Generated by Arkos Tracker 2.

simple_test_Start:
simple_test_StartDisarkGenerateExternalLabel:

simple_test_DisarkByteRegionStart0:
        .ascii "AT20"
simple_test_DisarkPointerRegionStart1:
        .word simple_test_ArpeggioTable #The address of the Arpeggio table.
        .word simple_test_PitchTable    #The address of the Pitch table.
        .word simple_test_InstrumentTable       #The address of the Instrument table.
        .word simple_test_EffectBlockTable      #The address of the Effect Block table.
simple_test_DisarkPointerRegionEnd1:


#The addresses of each Subsong:
simple_test_DisarkPointerRegionStart2:
        .word simple_test_Subsong0_Start
simple_test_DisarkPointerRegionEnd2:

#Declares all the Arpeggios.
simple_test_ArpeggioTable:
simple_test_DisarkPointerRegionStart3:
simple_test_DisarkPointerRegionEnd3:

#Declares all the Pitches.
simple_test_PitchTable:
simple_test_DisarkPointerRegionStart4:
simple_test_DisarkPointerRegionEnd4:

#Declares all the Instruments.
simple_test_InstrumentTable:
simple_test_DisarkPointerRegionStart5:
        .word simple_test_EmptyInstrument
        .word simple_test_Instrument1
simple_test_DisarkPointerRegionEnd5:

simple_test_EmptyInstrument:
        .byte 0 #The speed (>0, 0 for 256).
simple_test_EmptyInstrument_Loop:
        .byte 0 #No Soft no Hard. Volume: 0. Noise? false.

        .byte 6 #Loop to silence.

simple_test_Instrument1:
        .byte 1 #The speed (>0, 0 for 256).
        .byte 249       #Soft only. Volume: 15. Volume only.

        .byte 241       #Soft only. Volume: 14. Volume only.

        .byte 233       #Soft only. Volume: 13. Volume only.

        .byte 225       #Soft only. Volume: 12. Volume only.

        .byte 217       #Soft only. Volume: 11. Volume only.

        .byte 209       #Soft only. Volume: 10. Volume only.

        .byte 201       #Soft only. Volume: 9. Volume only.

        .byte 193       #Soft only. Volume: 8. Volume only.

        .byte 185       #Soft only. Volume: 7. Volume only.

        .byte 177       #Soft only. Volume: 6. Volume only.

        .byte 169       #Soft only. Volume: 5. Volume only.

        .byte 161       #Soft only. Volume: 4. Volume only.

        .byte 153       #Soft only. Volume: 3. Volume only.

        .byte 145       #Soft only. Volume: 2. Volume only.

        .byte 137       #Soft only. Volume: 1. Volume only.

        .byte 6 #Loop to silence.


#The indexes of the effect blocks used by this song.
simple_test_EffectBlockTable:

simple_test_DisarkByteRegionEnd0:

#Subsong 0
#----------------------
simple_test_Subsong0_DisarkByteRegionStart0:
simple_test_Subsong0_Start:
        .byte 2 #ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
        .byte 0 #Digichannel (0-2).
        .byte 1 #PSG count (>0).
        .byte 0 #Loop start index (>=0).
        .byte 0 #End index (>=0).
        .byte 6 #Initial speed (>=0).
        .byte 0 #Base note index (>=0).

        .even
simple_test_Subsong0_Linker:
simple_test_Subsong0_DisarkPointerRegionStart1:
#Position 0
simple_test_Subsong0_Linker_Loop:
        .word simple_test_Subsong0_Track0
        .word simple_test_Subsong0_Track1
        .word simple_test_Subsong0_Track2
        .word simple_test_Subsong0_LinkerBlock0

simple_test_Subsong0_DisarkPointerRegionEnd1:
        .word 0 #Loop.
simple_test_Subsong0_DisarkWordForceReference2:
        .word simple_test_Subsong0_Linker_Loop

simple_test_Subsong0_LinkerBlock0:
        .byte 64        #Height.
        .byte 0 #Transposition 0.
        .byte 0 #Transposition 1.
        .byte 0 #Transposition 2.
simple_test_Subsong0_DisarkWordForceReference3:
        .word simple_test_Subsong0_SpeedTrack0  #SpeedTrack address.
simple_test_Subsong0_DisarkWordForceReference4:
        .word simple_test_Subsong0_EventTrack0  #EventTrack address.

simple_test_Subsong0_Track0:
        .byte 164
        .byte 1 #New Instrument (1).
        .byte 61, 14    #Waits for 15 lines.

        .byte 36
        .byte 61, 14    #Waits for 15 lines.

        .byte 36
        .byte 61, 14    #Waits for 15 lines.

        .byte 36
        .byte 36
        .byte 61, 127   #Waits for 128 lines.


simple_test_Subsong0_Track1:
        .byte 62 + 2 * 64       #Optimized wait for 4 lines.

        .byte 166
        .byte 1 #New Instrument (1).
        .byte 61, 14    #Waits for 15 lines.

        .byte 38
        .byte 61, 14    #Waits for 15 lines.

        .byte 38
        .byte 61, 14    #Waits for 15 lines.

        .byte 38
        .byte 38
        .byte 61, 127   #Waits for 128 lines.


simple_test_Subsong0_Track2:
        .byte 61, 7     #Waits for 8 lines.

        .byte 168
        .byte 1 #New Instrument (1).
        .byte 61, 14    #Waits for 15 lines.

        .byte 40
        .byte 61, 14    #Waits for 15 lines.

        .byte 40
        .byte 61, 14    #Waits for 15 lines.

        .byte 40
        .byte 40
        .byte 61, 127   #Waits for 128 lines.


#The speed tracks
simple_test_Subsong0_SpeedTrack0:
        .byte 255       #Wait for 128 lines.

#The event tracks
simple_test_Subsong0_EventTrack0:
        .byte 255       #Wait for 128 lines.

simple_test_Subsong0_DisarkByteRegionEnd0:
        .even
