#Untitled, AKG format, v1.0.

#Generated by Arkos Tracker 2.

TomJerrySudokuMenu_Start:
TomJerrySudokuMenu_StartDisarkGenerateExternalLabel:

TomJerrySudokuMenu_DisarkByteRegionStart0:
	.ascii "AT20"
TomJerrySudokuMenu_DisarkPointerRegionStart1:
	.word TomJerrySudokuMenu_ArpeggioTable	#The address of the Arpeggio table.
	.word TomJerrySudokuMenu_PitchTable	#The address of the Pitch table.
	.word TomJerrySudokuMenu_InstrumentTable	#The address of the Instrument table.
	.word TomJerrySudokuMenu_EffectBlockTable	#The address of the Effect Block table.
TomJerrySudokuMenu_DisarkPointerRegionEnd1:


#The addresses of each Subsong:
TomJerrySudokuMenu_DisarkPointerRegionStart2:
	.word TomJerrySudokuMenu_Subsong0_Start
TomJerrySudokuMenu_DisarkPointerRegionEnd2:

#Declares all the Arpeggios.
TomJerrySudokuMenu_ArpeggioTable:
TomJerrySudokuMenu_DisarkPointerRegionStart3:
TomJerrySudokuMenu_DisarkPointerRegionEnd3:

#Declares all the Pitches.
TomJerrySudokuMenu_PitchTable:
TomJerrySudokuMenu_DisarkPointerRegionStart4:
TomJerrySudokuMenu_DisarkPointerRegionEnd4:

#Declares all the Instruments.
TomJerrySudokuMenu_InstrumentTable:
TomJerrySudokuMenu_DisarkPointerRegionStart5:
	.word TomJerrySudokuMenu_EmptyInstrument
	.word TomJerrySudokuMenu_Instrument1
	.word TomJerrySudokuMenu_Instrument2
	.word TomJerrySudokuMenu_Instrument3
TomJerrySudokuMenu_DisarkPointerRegionEnd5:

TomJerrySudokuMenu_EmptyInstrument:
	.byte 0	#The speed (>0, 0 for 256).
TomJerrySudokuMenu_EmptyInstrument_Loop:	.byte 0	#No Soft no Hard. Volume: 0. Noise? false.

	.byte 6	#Loop to silence.

TomJerrySudokuMenu_Instrument1:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 97	#Soft only. Volume: 12.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 12	#Arpeggio.

	.byte 217	#Soft only. Volume: 11. Volume only.

	.byte 81	#Soft only. Volume: 10.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 12	#Arpeggio.

TomJerrySudokuMenu_Instrument1_Loop:	.byte 185	#Soft only. Volume: 7. Volume only.

	.byte 57	#Soft only. Volume: 7.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 12	#Arpeggio.

	.byte 7	#Loop.
	.even
TomJerrySudokuMenu_DisarkWordForceReference6:
	.word TomJerrySudokuMenu_Instrument1_Loop	#Loop here.

TomJerrySudokuMenu_Instrument2:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 217	#Soft only. Volume: 11. Volume only.

	.byte 209	#Soft only. Volume: 10. Volume only.

	.byte 185	#Soft only. Volume: 7. Volume only.

TomJerrySudokuMenu_Instrument2_Loop:	.byte 169	#Soft only. Volume: 5. Volume only.

	.byte 0	#No Soft no Hard. Volume: 0. Noise? false.

	.byte 161	#Soft only. Volume: 4. Volume only.

	.byte 0	#No Soft no Hard. Volume: 0. Noise? false.

	.byte 7	#Loop.
	.even
TomJerrySudokuMenu_DisarkWordForceReference7:
	.word TomJerrySudokuMenu_Instrument2_Loop	#Loop here.

TomJerrySudokuMenu_Instrument3:
	.byte 4	#The speed (>0, 0 for 256).
	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 97	#Soft only. Volume: 12.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 12	#Arpeggio.

	.byte 193	#Soft only. Volume: 8. Volume only.

	.byte 65	#Soft only. Volume: 8.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 12	#Arpeggio.

	.byte 217	#Soft only. Volume: 11. Volume only.

	.byte 89	#Soft only. Volume: 11.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 12	#Arpeggio.

TomJerrySudokuMenu_Instrument3_Loop:	.byte 201	#Soft only. Volume: 9. Volume only.

	.byte 73	#Soft only. Volume: 9.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 12	#Arpeggio.

	.byte 193	#Soft only. Volume: 8. Volume only.

	.byte 65	#Soft only. Volume: 8.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 12	#Arpeggio.

	.byte 7	#Loop.
	.even
TomJerrySudokuMenu_DisarkWordForceReference8:
	.word TomJerrySudokuMenu_Instrument3_Loop	#Loop here.


#The indexes of the effect blocks used by this song.
TomJerrySudokuMenu_EffectBlockTable:
TomJerrySudokuMenu_DisarkPointerRegionStart9:
	.word TomJerrySudokuMenu_EffectBlock_P4P0	#Index 0
	.word TomJerrySudokuMenu_EffectBlock_P4P5	#Index 1
	.word TomJerrySudokuMenu_EffectBlock_P4P1	#Index 2
	.word TomJerrySudokuMenu_EffectBlock_P4P2	#Index 3
	.word TomJerrySudokuMenu_EffectBlock_P4P3	#Index 4
	.word TomJerrySudokuMenu_EffectBlock_P4P4	#Index 5
	.word TomJerrySudokuMenu_EffectBlock_P4P6	#Index 6
TomJerrySudokuMenu_DisarkPointerRegionEnd9:

TomJerrySudokuMenu_EffectBlock_P4P0:
	.byte 4, 0
TomJerrySudokuMenu_EffectBlock_P4P1:
	.byte 4, 1
TomJerrySudokuMenu_EffectBlock_P4P2:
	.byte 4, 2
TomJerrySudokuMenu_EffectBlock_P4P3:
	.byte 4, 3
TomJerrySudokuMenu_EffectBlock_P4P4:
	.byte 4, 4
TomJerrySudokuMenu_EffectBlock_P4P5:
	.byte 4, 5
TomJerrySudokuMenu_EffectBlock_P4P6:
	.byte 4, 6

TomJerrySudokuMenu_DisarkByteRegionEnd0:

#Subsong 0
#----------------------
TomJerrySudokuMenu_Subsong0_DisarkByteRegionStart0:
TomJerrySudokuMenu_Subsong0_Start:
	.byte 2	#ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	.byte 0	#Digichannel (0-2).
	.byte 1	#PSG count (>0).
	.byte 1	#Loop start index (>=0).
	.byte 12	#End index (>=0).
	.byte 4	#Initial speed (>=0).
	.byte 25	#Base note index (>=0).

	.even

TomJerrySudokuMenu_Subsong0_Linker:
TomJerrySudokuMenu_Subsong0_DisarkPointerRegionStart1:
#Position 0
	.word TomJerrySudokuMenu_Subsong0_Track1
	.word TomJerrySudokuMenu_Subsong0_Track0
	.word TomJerrySudokuMenu_Subsong0_Track1
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

#Position 1
TomJerrySudokuMenu_Subsong0_Linker_Loop:
	.word TomJerrySudokuMenu_Subsong0_Track1
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track3
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

#Position 2
	.word TomJerrySudokuMenu_Subsong0_Track1
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track4
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

#Position 3
	.word TomJerrySudokuMenu_Subsong0_Track7
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track3
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

#Position 4
	.word TomJerrySudokuMenu_Subsong0_Track9
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track4
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

#Position 5
	.word TomJerrySudokuMenu_Subsong0_Track7
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track8
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

#Position 6
	.word TomJerrySudokuMenu_Subsong0_Track11
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track10
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

#Position 7
	.word TomJerrySudokuMenu_Subsong0_Track5
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track4
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

#Position 8
	.word TomJerrySudokuMenu_Subsong0_Track12
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track3
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

#Position 9
	.word TomJerrySudokuMenu_Subsong0_Track6
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track4
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

#Position 10
	.word TomJerrySudokuMenu_Subsong0_Track13
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track3
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock1

#Position 11
	.word TomJerrySudokuMenu_Subsong0_Track6
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track4
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock2

#Position 12
	.word TomJerrySudokuMenu_Subsong0_Track14
	.word TomJerrySudokuMenu_Subsong0_Track2
	.word TomJerrySudokuMenu_Subsong0_Track15
	.word TomJerrySudokuMenu_Subsong0_LinkerBlock0

TomJerrySudokuMenu_Subsong0_DisarkPointerRegionEnd1:
	.word 0	#Loop.
TomJerrySudokuMenu_Subsong0_DisarkWordForceReference2:
	.word TomJerrySudokuMenu_Subsong0_Linker_Loop

TomJerrySudokuMenu_Subsong0_LinkerBlock0:
	.byte 64	#Height.
	.byte 0	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
TomJerrySudokuMenu_Subsong0_DisarkWordForceReference3:
	.word TomJerrySudokuMenu_Subsong0_SpeedTrack0	#SpeedTrack address.
TomJerrySudokuMenu_Subsong0_DisarkWordForceReference4:
	.word TomJerrySudokuMenu_Subsong0_EventTrack0	#EventTrack address.
TomJerrySudokuMenu_Subsong0_LinkerBlock1:
	.byte 64	#Height.
	.byte 12	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
TomJerrySudokuMenu_Subsong0_DisarkWordForceReference5:
	.word TomJerrySudokuMenu_Subsong0_SpeedTrack0	#SpeedTrack address.
TomJerrySudokuMenu_Subsong0_DisarkWordForceReference6:
	.word TomJerrySudokuMenu_Subsong0_EventTrack0	#EventTrack address.
TomJerrySudokuMenu_Subsong0_LinkerBlock2:
	.byte 64	#Height.
	.byte -12	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
TomJerrySudokuMenu_Subsong0_DisarkWordForceReference7:
	.word TomJerrySudokuMenu_Subsong0_SpeedTrack0	#SpeedTrack address.
TomJerrySudokuMenu_Subsong0_DisarkWordForceReference8:
	.word TomJerrySudokuMenu_Subsong0_EventTrack0	#EventTrack address.

TomJerrySudokuMenu_Subsong0_Track0:
	.byte 230
	.byte 2	#New Instrument (2).
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 104
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 102
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 114
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 114
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 0	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track1:
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track2:
	.byte 230
	.byte 2	#New Instrument (2).
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 105
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 102
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 114
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 114
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 102
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 102
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 114
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 114
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 112
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 109
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 1	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track3:
	.byte 191
	.byte 15	#Escape note (15).
	.byte 3	#New Instrument (3).
	.byte 61, 26	#Waits for 27 lines.

	.byte 2
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 5
	.byte 61, 22	#Waits for 23 lines.

	.byte 5
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track4:
	.byte 135
	.byte 3	#New Instrument (3).
	.byte 61, 26	#Waits for 27 lines.

	.byte 7
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 0
	.byte 61, 26	#Waits for 27 lines.

	.byte 0
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track5:
	.byte 173
	.byte 1	#New Instrument (1).
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 36
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 36
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 36
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 36
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track6:
	.byte 183
	.byte 1	#New Instrument (1).
	.byte 61, 6	#Waits for 7 lines.

	.byte 55
	.byte 60	#Waits for 1 line.

	.byte 63
	.byte 82	#Escape note (82).
	.byte 60	#Waits for 1 line.

	.byte 55
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 55
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 63
	.byte 82	#Escape note (82).
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 55
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 63
	.byte 82	#Escape note (82).
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 55
	.byte 61, 18	#Waits for 19 lines.

	.byte 63
	.byte 82	#Escape note (82).
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 63
	.byte 85	#Escape note (85).
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 63
	.byte 87	#Escape note (87).
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track7:
	.byte 164
	.byte 1	#New Instrument (1).
	.byte 61, 6	#Waits for 7 lines.

	.byte 38
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 41
	.byte 61, 6	#Waits for 7 lines.

	.byte 43
	.byte 61, 6	#Waits for 7 lines.

	.byte 45
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 48
	.byte 61, 6	#Waits for 7 lines.

	.byte 45
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 43
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 41
	.byte 61, 6	#Waits for 7 lines.

	.byte 38
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track8:
	.byte 191
	.byte 15	#Escape note (15).
	.byte 3	#New Instrument (3).
	.byte 61, 26	#Waits for 27 lines.

	.byte 2
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 63
	.byte 22	#Escape note (22).
	.byte 61, 26	#Waits for 27 lines.

	.byte 9
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track9:
	.byte 164
	.byte 1	#New Instrument (1).
	.byte 61, 6	#Waits for 7 lines.

	.byte 38
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 41
	.byte 61, 6	#Waits for 7 lines.

	.byte 43
	.byte 61, 6	#Waits for 7 lines.

	.byte 50
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 48
	.byte 61, 6	#Waits for 7 lines.

	.byte 45
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 43
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 45
	.byte 61, 6	#Waits for 7 lines.

	.byte 36
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track10:
	.byte 191
	.byte 23	#Escape note (23).
	.byte 3	#New Instrument (3).
	.byte 61, 26	#Waits for 27 lines.

	.byte 10
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 0
	.byte 61, 26	#Waits for 27 lines.

	.byte 128
	.byte 1	#New Instrument (1).
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track11:
	.byte 164
	.byte 1	#New Instrument (1).
	.byte 61, 6	#Waits for 7 lines.

	.byte 38
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 41
	.byte 61, 6	#Waits for 7 lines.

	.byte 43
	.byte 61, 6	#Waits for 7 lines.

	.byte 45
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 43
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track12:
	.byte 176
	.byte 1	#New Instrument (1).
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 48
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 36
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 50
	.byte 60	#Waits for 1 line.

	.byte 48
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 48
	.byte 60	#Waits for 1 line.

	.byte 50
	.byte 60	#Waits for 1 line.

	.byte 48
	.byte 60	#Waits for 1 line.

	.byte 45
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 36
	.byte 60	#Waits for 1 line.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track13:
	.byte 169
	.byte 1	#New Instrument (1).
	.byte 61, 18	#Waits for 19 lines.

	.byte 36
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 38
	.byte 60	#Waits for 1 line.

	.byte 41
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 45
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track14:
	.byte 166
	.byte 1	#New Instrument (1).
	.byte 61, 22	#Waits for 23 lines.

	.byte 36
	.byte 60	#Waits for 1 line.

	.byte 33
	.byte 60	#Waits for 1 line.

	.byte 31
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 33
	.byte 61, 14	#Waits for 15 lines.

	.byte 124	#No note, but effects.
	.byte 2	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 3	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 4	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 5	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 6	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 128
	.byte 0	#New Instrument (0).
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


TomJerrySudokuMenu_Subsong0_Track15:
	.byte 191
	.byte 23	#Escape note (23).
	.byte 3	#New Instrument (3).
	.byte 61, 26	#Waits for 27 lines.

	.byte 10
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 2
	.byte 61, 26	#Waits for 27 lines.

	.byte 7
	.byte 61, 127	#Waits for 128 lines.


#The speed tracks
TomJerrySudokuMenu_Subsong0_SpeedTrack0:
	.byte 255	#Wait for 128 lines.

#The event tracks
TomJerrySudokuMenu_Subsong0_EventTrack0:
	.byte 255	#Wait for 128 lines.

TomJerrySudokuMenu_Subsong0_DisarkByteRegionEnd0:
