#A Harmless Grenade, AKG format, v1.0.

#Generated by Arkos Tracker 2.

AHarmlessGrenade_Start:
AHarmlessGrenade_StartDisarkGenerateExternalLabel:

AHarmlessGrenade_DisarkByteRegionStart0:
	.ascii "AT20"
AHarmlessGrenade_DisarkPointerRegionStart1:
        .even
	.word AHarmlessGrenade_ArpeggioTable	#The address of the Arpeggio table.
	.word AHarmlessGrenade_PitchTable	#The address of the Pitch table.
	.word AHarmlessGrenade_InstrumentTable	#The address of the Instrument table.
	.word AHarmlessGrenade_EffectBlockTable	#The address of the Effect Block table.
AHarmlessGrenade_DisarkPointerRegionEnd1:


#The addresses of each Subsong:
AHarmlessGrenade_DisarkPointerRegionStart2:
        .even
	.word AHarmlessGrenade_Subsong0_Start
AHarmlessGrenade_DisarkPointerRegionEnd2:

#Declares all the Arpeggios.
AHarmlessGrenade_ArpeggioTable:
AHarmlessGrenade_DisarkPointerRegionStart3:
        .even
	.word AHarmlessGrenade_Arpeggio1
	.word AHarmlessGrenade_Arpeggio2
AHarmlessGrenade_DisarkPointerRegionEnd3:

AHarmlessGrenade_Arpeggio1:
	.byte 1	#The speed.

	.byte 0
	.byte 12
	.byte 9
	.byte -12
	.byte 18
	.byte -128
AHarmlessGrenade_DisarkWordForceReference4:
        .even
	.word AHarmlessGrenade_Arpeggio1 + 0 + 1	#Loop.

AHarmlessGrenade_Arpeggio2:
	.byte 1	#The speed.

	.byte 0
	.byte 6
	.byte -3
	.byte -12
	.byte -6
	.byte 0
	.byte 12
	.byte -128
AHarmlessGrenade_DisarkWordForceReference5:
        .even
	.word AHarmlessGrenade_Arpeggio2 + 0 + 1	#Loop.

#Declares all the Pitches.
AHarmlessGrenade_PitchTable:
AHarmlessGrenade_DisarkPointerRegionStart6:
        .even
	.word AHarmlessGrenade_Pitch1
AHarmlessGrenade_DisarkPointerRegionEnd6:

AHarmlessGrenade_Pitch1:
	.word 2	#The speed.

	.word 0
AHarmlessGrenade_DisarkWordForceReference7:
        .even
	.word . + 2
	.word 0
AHarmlessGrenade_DisarkWordForceReference8:
        .even
	.word . + 2
	.word 0
AHarmlessGrenade_DisarkWordForceReference9:
        .even
	.word . + 2
	.word -1
AHarmlessGrenade_DisarkWordForceReference10:
        .even
	.word . + 2
	.word -4
AHarmlessGrenade_DisarkWordForceReference11:
        .even
	.word . + 2
	.word 2
AHarmlessGrenade_DisarkWordForceReference12:
        .even
	.word AHarmlessGrenade_Pitch1 + 4 * 2 + 2

#Declares all the Instruments.
AHarmlessGrenade_InstrumentTable:
AHarmlessGrenade_DisarkPointerRegionStart13:
        .even
	.word AHarmlessGrenade_EmptyInstrument
	.word AHarmlessGrenade_Instrument1
	.word AHarmlessGrenade_Instrument2
	.word AHarmlessGrenade_Instrument3
	.word AHarmlessGrenade_Instrument4
	.word AHarmlessGrenade_Instrument5
	.word AHarmlessGrenade_Instrument6
	.word AHarmlessGrenade_Instrument7
	.word AHarmlessGrenade_Instrument8
	.word AHarmlessGrenade_Instrument9
	.word AHarmlessGrenade_Instrument10
	.word AHarmlessGrenade_Instrument11
	.word AHarmlessGrenade_Instrument12
	.word AHarmlessGrenade_Instrument13
	.word AHarmlessGrenade_Instrument14
	.word AHarmlessGrenade_Instrument15
	.word AHarmlessGrenade_Instrument16
	.word AHarmlessGrenade_Instrument17
	.word AHarmlessGrenade_Instrument18
	.word AHarmlessGrenade_Instrument19
AHarmlessGrenade_DisarkPointerRegionEnd13:

AHarmlessGrenade_EmptyInstrument:
	.byte 0	#The speed (>0, 0 for 256).
AHarmlessGrenade_EmptyInstrument_Loop:	.byte 0	#No Soft no Hard. Volume: 0. Noise? false.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument1:
	.byte 2	#The speed (>0, 0 for 256).
	.byte 2	#Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	.byte 34	#Complex case. Ratio: 5
	.byte 12	#Arpeggio.

	.byte 2	#Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	.byte 36	#Complex case. Ratio: 3
	.byte 12	#Arpeggio.

	.byte 2	#Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	.byte 36	#Complex case. Ratio: 3
	.byte 12	#Arpeggio.

	.byte 2	#Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	.byte 130	#Simple case. Ratio: 5

	.byte 81	#Soft only. Volume: 10.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 12	#Arpeggio.

	.byte 209	#Soft only. Volume: 10. Volume only.

	.byte 81	#Soft only. Volume: 10.
	.byte 64	#Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.byte 12	#Arpeggio.

	.byte 201	#Soft only. Volume: 9. Volume only.

	.byte 193	#Soft only. Volume: 8. Volume only.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument2:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 121	#Soft only. Volume: 15.
	.byte 2	#Additional data. Noise: 2. Pitch? false. Arp? false. Period? false.

	.byte 121	#Soft only. Volume: 15.
	.byte 33	#Additional data. Noise: 1. Pitch? true. Arp? false. Period? false.
	.word 32	#Pitch.

	.byte 121	#Soft only. Volume: 15.
	.byte 32	#Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	.word 48	#Pitch.

	.byte 121	#Soft only. Volume: 15.
	.byte 32	#Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	.word 68	#Pitch.

	.byte 121	#Soft only. Volume: 15.
	.byte 32	#Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	.word 116	#Pitch.

	.byte 121	#Soft only. Volume: 15.
	.byte 32	#Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	.word 228	#Pitch.

	.byte 113	#Soft only. Volume: 14.
	.byte 32	#Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	.word 180	#Pitch.

	.byte 105	#Soft only. Volume: 13.
	.byte 32	#Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	.word 292	#Pitch.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument3:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 248	#No Soft no Hard. Volume: 15. Noise? true.
	.byte 1	#Noise: 1.

	.byte 216	#No Soft no Hard. Volume: 11. Noise? true.
	.byte 1	#Noise: 1.

	.byte 184	#No Soft no Hard. Volume: 7. Noise? true.
	.byte 1	#Noise: 1.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument4:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 248	#No Soft no Hard. Volume: 15. Noise? true.
	.byte 4	#Noise: 4.

	.byte 200	#No Soft no Hard. Volume: 9. Noise? true.
	.byte 1	#Noise: 1.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument5:
	.byte 1	#The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument5_Loop:	.byte 248	#No Soft no Hard. Volume: 15. Noise? true.
	.byte 1	#Noise: 1.

	.byte 200	#No Soft no Hard. Volume: 9. Noise? true.
	.byte 1	#Noise: 1.

	.byte 176	#No Soft no Hard. Volume: 6. Noise? true.
	.byte 1	#Noise: 1.

	.byte 7	#Loop.
AHarmlessGrenade_DisarkWordForceReference14:
        .even
	.word AHarmlessGrenade_Instrument5_Loop	#Loop here.

AHarmlessGrenade_Instrument6:
	.byte 4	#The speed (>0, 0 for 256).
	.byte 248	#No Soft no Hard. Volume: 15. Noise? true.
	.byte 1	#Noise: 1.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument7:
	.byte 3	#The speed (>0, 0 for 256).
	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 233	#Soft only. Volume: 13. Volume only.

	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 217	#Soft only. Volume: 11. Volume only.

	.byte 209	#Soft only. Volume: 10. Volume only.

	.byte 201	#Soft only. Volume: 9. Volume only.

	.byte 193	#Soft only. Volume: 8. Volume only.

	.byte 185	#Soft only. Volume: 7. Volume only.

	.byte 177	#Soft only. Volume: 6. Volume only.

	.byte 169	#Soft only. Volume: 5. Volume only.

	.byte 161	#Soft only. Volume: 4. Volume only.

	.byte 153	#Soft only. Volume: 3. Volume only.

	.byte 145	#Soft only. Volume: 2. Volume only.

	.byte 137	#Soft only. Volume: 1. Volume only.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument8:
	.byte 1	#The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument8_Loop:	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 131	#Simple case. Ratio: 4

	.byte 7	#Loop.
AHarmlessGrenade_DisarkWordForceReference15:
        .even
	.word AHarmlessGrenade_Instrument8_Loop	#Loop here.

AHarmlessGrenade_Instrument9:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 248	#No Soft no Hard. Volume: 15. Noise? true.
	.byte 2	#Noise: 2.

	.byte 241	#Soft only. Volume: 14. Volume only.

	.byte 105	#Soft only. Volume: 13.
	.byte 33	#Additional data. Noise: 1. Pitch? true. Arp? false. Period? false.
	.word 208	#Pitch.

	.byte 89	#Soft only. Volume: 11.
	.byte 33	#Additional data. Noise: 1. Pitch? true. Arp? false. Period? false.
	.word 400	#Pitch.

	.byte 216	#No Soft no Hard. Volume: 11. Noise? true.
	.byte 1	#Noise: 1.

	.byte 216	#No Soft no Hard. Volume: 11. Noise? true.
	.byte 3	#Noise: 3.

	.byte 208	#No Soft no Hard. Volume: 10. Noise? true.
	.byte 4	#Noise: 4.

	.byte 200	#No Soft no Hard. Volume: 9. Noise? true.
	.byte 1	#Noise: 1.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument10:
	.byte 5	#The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument10_Loop:	.byte 2	#Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	.byte 130	#Simple case. Ratio: 5

	.byte 7	#Loop.
AHarmlessGrenade_DisarkWordForceReference16:
        .even
	.word AHarmlessGrenade_Instrument10_Loop	#Loop here.

AHarmlessGrenade_Instrument11:
	.byte 2	#The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument11_Loop:	.byte 2	#Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	.byte 35	#Complex case. Ratio: 4
	.byte 12	#Arpeggio.

	.byte 2	#Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	.byte 35	#Complex case. Ratio: 4
	.byte 12	#Arpeggio.

	.byte 120	#No Soft no Hard. Volume: 15. Noise? false.

	.byte 7	#Loop.
AHarmlessGrenade_DisarkWordForceReference17:
        .even
	.word AHarmlessGrenade_Instrument11_Loop	#Loop here.

AHarmlessGrenade_Instrument12:
	.byte 1	#The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument12_Loop:	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 7	#Loop.
AHarmlessGrenade_DisarkWordForceReference18:
        .even
	.word AHarmlessGrenade_Instrument12_Loop	#Loop here.

AHarmlessGrenade_Instrument13:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument14:
	.byte 1	#The speed (>0, 0 for 256).
AHarmlessGrenade_Instrument14_Loop:	.byte 34	#Soft to Hard. Envelope: 10. Retrig ? false. Noise ? false.
	.byte 132	#Simple case. Ratio: 3

	.byte 7	#Loop.
AHarmlessGrenade_DisarkWordForceReference19:
        .even
	.word AHarmlessGrenade_Instrument14_Loop	#Loop here.

AHarmlessGrenade_Instrument15:
	.byte 2	#The speed (>0, 0 for 256).
	.byte 249	#Soft only. Volume: 15. Volume only.

AHarmlessGrenade_Instrument15_Loop:	.byte 113	#Soft only. Volume: 14.
	.byte 32	#Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	.word -5	#Pitch.

	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 89	#Soft only. Volume: 11.
	.byte 32	#Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	.word 5	#Pitch.

	.byte 249	#Soft only. Volume: 15. Volume only.

	.byte 105	#Soft only. Volume: 13.
	.byte 32	#Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	.word -7	#Pitch.

	.byte 201	#Soft only. Volume: 9. Volume only.

	.byte 81	#Soft only. Volume: 10.
	.byte 32	#Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	.word 32	#Pitch.

	.byte 217	#Soft only. Volume: 11. Volume only.

	.byte 225	#Soft only. Volume: 12. Volume only.

	.byte 241	#Soft only. Volume: 14. Volume only.

	.byte 7	#Loop.
AHarmlessGrenade_DisarkWordForceReference20:
        .even
	.word AHarmlessGrenade_Instrument15_Loop	#Loop here.

AHarmlessGrenade_Instrument16:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 232	#No Soft no Hard. Volume: 13. Noise? true.
	.byte 5	#Noise: 5.

	.byte 216	#No Soft no Hard. Volume: 11. Noise? true.
	.byte 5	#Noise: 5.

	.byte 208	#No Soft no Hard. Volume: 10. Noise? true.
	.byte 5	#Noise: 5.

	.byte 200	#No Soft no Hard. Volume: 9. Noise? true.
	.byte 5	#Noise: 5.

	.byte 184	#No Soft no Hard. Volume: 7. Noise? true.
	.byte 5	#Noise: 5.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument17:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 232	#No Soft no Hard. Volume: 13. Noise? true.
	.byte 9	#Noise: 9.

	.byte 216	#No Soft no Hard. Volume: 11. Noise? true.
	.byte 9	#Noise: 9.

	.byte 208	#No Soft no Hard. Volume: 10. Noise? true.
	.byte 9	#Noise: 9.

	.byte 200	#No Soft no Hard. Volume: 9. Noise? true.
	.byte 9	#Noise: 9.

	.byte 184	#No Soft no Hard. Volume: 7. Noise? true.
	.byte 9	#Noise: 9.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument18:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 232	#No Soft no Hard. Volume: 13. Noise? true.
	.byte 17	#Noise: 17.

	.byte 216	#No Soft no Hard. Volume: 11. Noise? true.
	.byte 17	#Noise: 17.

	.byte 208	#No Soft no Hard. Volume: 10. Noise? true.
	.byte 17	#Noise: 17.

	.byte 200	#No Soft no Hard. Volume: 9. Noise? true.
	.byte 17	#Noise: 17.

	.byte 184	#No Soft no Hard. Volume: 7. Noise? true.
	.byte 17	#Noise: 17.

	.byte 6	#Loop to silence.

AHarmlessGrenade_Instrument19:
	.byte 1	#The speed (>0, 0 for 256).
	.byte 232	#No Soft no Hard. Volume: 13. Noise? true.
	.byte 25	#Noise: 25.

	.byte 216	#No Soft no Hard. Volume: 11. Noise? true.
	.byte 25	#Noise: 25.

	.byte 208	#No Soft no Hard. Volume: 10. Noise? true.
	.byte 25	#Noise: 25.

	.byte 200	#No Soft no Hard. Volume: 9. Noise? true.
	.byte 25	#Noise: 25.

	.byte 184	#No Soft no Hard. Volume: 7. Noise? true.
	.byte 25	#Noise: 25.

	.byte 6	#Loop to silence.


#The indexes of the effect blocks used by this song.
AHarmlessGrenade_EffectBlockTable:
AHarmlessGrenade_DisarkPointerRegionStart21:
        .even
	.word AHarmlessGrenade_EffectBlock_P20P0P32	#Index 0
	.word AHarmlessGrenade_EffectBlock_P4P3	#Index 1
	.word AHarmlessGrenade_EffectBlock_P4P0	#Index 2
	.word AHarmlessGrenade_EffectBlock_P4P2	#Index 3
	.word AHarmlessGrenade_EffectBlock_P4P1	#Index 4
	.word AHarmlessGrenade_EffectBlock_P24P26P255P15	#Index 5
	.word AHarmlessGrenade_EffectBlock_P28P48	#Index 6
	.word AHarmlessGrenade_EffectBlock_P3P5P21P0P2P6P1	#Index 7
	.word AHarmlessGrenade_EffectBlock_P0	#Index 8
	.word AHarmlessGrenade_EffectBlock_P20P0P16	#Index 9
	.word AHarmlessGrenade_EffectBlock_P28P57	#Index 10
	.word AHarmlessGrenade_EffectBlock_P28P51	#Index 11
	.word AHarmlessGrenade_EffectBlock_P4P4	#Index 12
	.word AHarmlessGrenade_EffectBlock_P3P2P10P0	#Index 13
	.word AHarmlessGrenade_EffectBlock_P3P2P6P0	#Index 14
	.word AHarmlessGrenade_EffectBlock_P5P2P10P0	#Index 15
	.word AHarmlessGrenade_EffectBlock_P28P54	#Index 16
	.word AHarmlessGrenade_EffectBlock_P28P58	#Index 17
	.word AHarmlessGrenade_EffectBlock_P4P5	#Index 18
	.word AHarmlessGrenade_EffectBlock_P14P0P1	#Index 19
	.word AHarmlessGrenade_EffectBlock_P20P0P80	#Index 20
	.word AHarmlessGrenade_EffectBlock_P28P55	#Index 21
	.word AHarmlessGrenade_EffectBlock_P4P6	#Index 22
	.word AHarmlessGrenade_EffectBlock_P2P4	#Index 23
	.word AHarmlessGrenade_EffectBlock_P2P2	#Index 24
AHarmlessGrenade_DisarkPointerRegionEnd21:

AHarmlessGrenade_EffectBlock_P0:
	.byte 0
AHarmlessGrenade_EffectBlock_P2P2:
	.byte 2, 2
AHarmlessGrenade_EffectBlock_P2P4:
	.byte 2, 4
AHarmlessGrenade_EffectBlock_P4P0:
	.byte 4, 0
AHarmlessGrenade_EffectBlock_P4P1:
	.byte 4, 1
AHarmlessGrenade_EffectBlock_P4P2:
	.byte 4, 2
AHarmlessGrenade_EffectBlock_P4P3:
	.byte 4, 3
AHarmlessGrenade_EffectBlock_P4P4:
	.byte 4, 4
AHarmlessGrenade_EffectBlock_P4P5:
	.byte 4, 5
AHarmlessGrenade_EffectBlock_P4P6:
	.byte 4, 6
AHarmlessGrenade_EffectBlock_P28P48:
	.byte 28, 48
AHarmlessGrenade_EffectBlock_P28P51:
	.byte 28, 51
AHarmlessGrenade_EffectBlock_P28P54:
	.byte 28, 54
AHarmlessGrenade_EffectBlock_P28P55:
	.byte 28, 55
AHarmlessGrenade_EffectBlock_P28P57:
	.byte 28, 57
AHarmlessGrenade_EffectBlock_P28P58:
	.byte 28, 58
AHarmlessGrenade_EffectBlock_P14P0P1:
	.byte 14, 0, 1
AHarmlessGrenade_EffectBlock_P20P0P16:
	.byte 20, 0, 16
AHarmlessGrenade_EffectBlock_P20P0P32:
	.byte 20, 0, 32
AHarmlessGrenade_EffectBlock_P20P0P80:
	.byte 20, 0, 80
AHarmlessGrenade_EffectBlock_P3P2P6P0:
	.byte 3, 2, 6, 0
AHarmlessGrenade_EffectBlock_P3P2P10P0:
	.byte 3, 2, 10, 0
AHarmlessGrenade_EffectBlock_P5P2P10P0:
	.byte 5, 2, 10, 0
AHarmlessGrenade_EffectBlock_P3P5P21P0P2P6P1:
	.byte 3, 5, 21, 0, 2, 6, 1
AHarmlessGrenade_EffectBlock_P24P26P255P15:
	.byte 24, 26, 255, 15

AHarmlessGrenade_DisarkByteRegionEnd0:

#Subsong 0
#----------------------
AHarmlessGrenade_Subsong0_DisarkByteRegionStart0:
AHarmlessGrenade_Subsong0_Start:
	.byte 2	#ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	.byte 0	#Digichannel (0-2).
	.byte 1	#PSG count (>0).
	.byte 0	#Loop start index (>=0).
	.byte 23	#End index (>=0).
	.byte 6	#Initial speed (>=0).
	.byte 5	#Base note index (>=0).

AHarmlessGrenade_Subsong0_Linker:
AHarmlessGrenade_Subsong0_DisarkPointerRegionStart1:
        .even
#Position 0
AHarmlessGrenade_Subsong0_Linker_Loop:
	.word AHarmlessGrenade_Subsong0_Track0
	.word AHarmlessGrenade_Subsong0_Track22
	.word AHarmlessGrenade_Subsong0_Track22
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 1
	.word AHarmlessGrenade_Subsong0_Track0
	.word AHarmlessGrenade_Subsong0_Track1
	.word AHarmlessGrenade_Subsong0_Track1
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 2
	.word AHarmlessGrenade_Subsong0_Track0
	.word AHarmlessGrenade_Subsong0_Track1
	.word AHarmlessGrenade_Subsong0_Track2
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 3
	.word AHarmlessGrenade_Subsong0_Track0
	.word AHarmlessGrenade_Subsong0_Track1
	.word AHarmlessGrenade_Subsong0_Track2
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 4
	.word AHarmlessGrenade_Subsong0_Track3
	.word AHarmlessGrenade_Subsong0_Track5
	.word AHarmlessGrenade_Subsong0_Track4
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 5
	.word AHarmlessGrenade_Subsong0_Track6
	.word AHarmlessGrenade_Subsong0_Track8
	.word AHarmlessGrenade_Subsong0_Track7
	.word AHarmlessGrenade_Subsong0_LinkerBlock1

#Position 6
	.word AHarmlessGrenade_Subsong0_Track9
	.word AHarmlessGrenade_Subsong0_Track10
	.word AHarmlessGrenade_Subsong0_Track11
	.word AHarmlessGrenade_Subsong0_LinkerBlock2

#Position 7
	.word AHarmlessGrenade_Subsong0_Track6
	.word AHarmlessGrenade_Subsong0_Track8
	.word AHarmlessGrenade_Subsong0_Track7
	.word AHarmlessGrenade_Subsong0_LinkerBlock1

#Position 8
	.word AHarmlessGrenade_Subsong0_Track12
	.word AHarmlessGrenade_Subsong0_Track13
	.word AHarmlessGrenade_Subsong0_Track14
	.word AHarmlessGrenade_Subsong0_LinkerBlock2

#Position 9
	.word AHarmlessGrenade_Subsong0_Track6
	.word AHarmlessGrenade_Subsong0_Track8
	.word AHarmlessGrenade_Subsong0_Track7
	.word AHarmlessGrenade_Subsong0_LinkerBlock1

#Position 10
	.word AHarmlessGrenade_Subsong0_Track9
	.word AHarmlessGrenade_Subsong0_Track10
	.word AHarmlessGrenade_Subsong0_Track11
	.word AHarmlessGrenade_Subsong0_LinkerBlock2

#Position 11
	.word AHarmlessGrenade_Subsong0_Track15
	.word AHarmlessGrenade_Subsong0_Track16
	.word AHarmlessGrenade_Subsong0_Track17
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 12
	.word AHarmlessGrenade_Subsong0_Track15
	.word AHarmlessGrenade_Subsong0_Track16
	.word AHarmlessGrenade_Subsong0_Track20
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 13
	.word AHarmlessGrenade_Subsong0_Track15
	.word AHarmlessGrenade_Subsong0_Track16
	.word AHarmlessGrenade_Subsong0_Track17
	.word AHarmlessGrenade_Subsong0_LinkerBlock3

#Position 14
	.word AHarmlessGrenade_Subsong0_Track22
	.word AHarmlessGrenade_Subsong0_Track23
	.word AHarmlessGrenade_Subsong0_Track22
	.word AHarmlessGrenade_Subsong0_LinkerBlock4

#Position 15
	.word AHarmlessGrenade_Subsong0_Track18
	.word AHarmlessGrenade_Subsong0_Track19
	.word AHarmlessGrenade_Subsong0_Track21
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 16
	.word AHarmlessGrenade_Subsong0_Track18
	.word AHarmlessGrenade_Subsong0_Track19
	.word AHarmlessGrenade_Subsong0_Track21
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 17
	.word AHarmlessGrenade_Subsong0_Track24
	.word AHarmlessGrenade_Subsong0_Track19
	.word AHarmlessGrenade_Subsong0_Track21
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 18
	.word AHarmlessGrenade_Subsong0_Track24
	.word AHarmlessGrenade_Subsong0_Track19
	.word AHarmlessGrenade_Subsong0_Track21
	.word AHarmlessGrenade_Subsong0_LinkerBlock0

#Position 19
	.word AHarmlessGrenade_Subsong0_Track24
	.word AHarmlessGrenade_Subsong0_Track19
	.word AHarmlessGrenade_Subsong0_Track21
	.word AHarmlessGrenade_Subsong0_LinkerBlock5

#Position 20
	.word AHarmlessGrenade_Subsong0_Track22
	.word AHarmlessGrenade_Subsong0_Track23
	.word AHarmlessGrenade_Subsong0_Track25
	.word AHarmlessGrenade_Subsong0_LinkerBlock6

#Position 21
	.word AHarmlessGrenade_Subsong0_Track22
	.word AHarmlessGrenade_Subsong0_Track23
	.word AHarmlessGrenade_Subsong0_Track25
	.word AHarmlessGrenade_Subsong0_LinkerBlock7

#Position 22
	.word AHarmlessGrenade_Subsong0_Track22
	.word AHarmlessGrenade_Subsong0_Track23
	.word AHarmlessGrenade_Subsong0_Track25
	.word AHarmlessGrenade_Subsong0_LinkerBlock8

#Position 23
	.word AHarmlessGrenade_Subsong0_Track22
	.word AHarmlessGrenade_Subsong0_Track23
	.word AHarmlessGrenade_Subsong0_Track25
	.word AHarmlessGrenade_Subsong0_LinkerBlock9

AHarmlessGrenade_Subsong0_DisarkPointerRegionEnd1:
	.word 0	#Loop.
AHarmlessGrenade_Subsong0_DisarkWordForceReference2:
        .even
	.word AHarmlessGrenade_Subsong0_Linker_Loop

AHarmlessGrenade_Subsong0_LinkerBlock0:
	.byte 32	#Height.
	.byte 0	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference3:
        .even
	.word AHarmlessGrenade_Subsong0_SpeedTrack0	#SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference4:
        .even
	.word AHarmlessGrenade_Subsong0_EventTrack0	#EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock1:
	.byte 24	#Height.
	.byte 0	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference5:
        .even
	.word AHarmlessGrenade_Subsong0_SpeedTrack0	#SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference6:
        .even
	.word AHarmlessGrenade_Subsong0_EventTrack0	#EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock2:
	.byte 8	#Height.
	.byte 0	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference7:
        .even
	.word AHarmlessGrenade_Subsong0_SpeedTrack0	#SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference8:
        .even
	.word AHarmlessGrenade_Subsong0_EventTrack0	#EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock3:
	.byte 28	#Height.
	.byte 0	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference9:
        .even
	.word AHarmlessGrenade_Subsong0_SpeedTrack0	#SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference10:
        .even
	.word AHarmlessGrenade_Subsong0_EventTrack0	#EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock4:
	.byte 4	#Height.
	.byte 0	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 0	#Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference11:
        .even
	.word AHarmlessGrenade_Subsong0_SpeedTrack0	#SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference12:
        .even
	.word AHarmlessGrenade_Subsong0_EventTrack0	#EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock5:
	.byte 16	#Height.
	.byte 2	#Transposition 0.
	.byte 0	#Transposition 1.
	.byte 2	#Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference13:
        .even
	.word AHarmlessGrenade_Subsong0_SpeedTrack0	#SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference14:
        .even
	.word AHarmlessGrenade_Subsong0_EventTrack0	#EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock6:
	.byte 4	#Height.
	.byte 0	#Transposition 0.
	.byte 2	#Transposition 1.
	.byte 0	#Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference15:
        .even
	.word AHarmlessGrenade_Subsong0_SpeedTrack0	#SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference16:
        .even
	.word AHarmlessGrenade_Subsong0_EventTrack0	#EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock7:
	.byte 4	#Height.
	.byte 0	#Transposition 0.
	.byte 10	#Transposition 1.
	.byte 4	#Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference17:
        .even
	.word AHarmlessGrenade_Subsong0_SpeedTrack0	#SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference18:
        .even
	.word AHarmlessGrenade_Subsong0_EventTrack0	#EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock8:
	.byte 4	#Height.
	.byte 0	#Transposition 0.
	.byte 20	#Transposition 1.
	.byte 8	#Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference19:
        .even
	.word AHarmlessGrenade_Subsong0_SpeedTrack0	#SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference20:
        .even
	.word AHarmlessGrenade_Subsong0_EventTrack0	#EventTrack address.
AHarmlessGrenade_Subsong0_LinkerBlock9:
	.byte 4	#Height.
	.byte 0	#Transposition 0.
	.byte 36	#Transposition 1.
	.byte 14	#Transposition 2.
AHarmlessGrenade_Subsong0_DisarkWordForceReference21:
        .even
	.word AHarmlessGrenade_Subsong0_SpeedTrack0	#SpeedTrack address.
AHarmlessGrenade_Subsong0_DisarkWordForceReference22:
        .even
	.word AHarmlessGrenade_Subsong0_EventTrack0	#EventTrack address.

AHarmlessGrenade_Subsong0_Track0:
	.byte 146
	.byte 1	#New Instrument (1).
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 18
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 18
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 18
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 18
	.byte 21
	.byte 24
	.byte 27
	.byte 30
	.byte 24
	.byte 19
	.byte 21
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track1:
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track2:
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 8	#Index to an effect block.
	.byte 211
	.byte 3	#New Instrument (3).
	.byte 1	#Index to an effect block.
	.byte 83
	.byte 2	#Index to an effect block.
	.byte 83
	.byte 1	#Index to an effect block.
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 2	#Index to an effect block.
	.byte 211
	.byte 4	#New Instrument (4).
	.byte 4	#Index to an effect block.
	.byte 211
	.byte 3	#New Instrument (3).
	.byte 3	#Index to an effect block.
	.byte 83
	.byte 1	#Index to an effect block.
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 2	#Index to an effect block.
	.byte 211
	.byte 5	#New Instrument (5).
	.byte 4	#Index to an effect block.
	.byte 211
	.byte 3	#New Instrument (3).
	.byte 3	#Index to an effect block.
	.byte 211
	.byte 4	#New Instrument (4).
	.byte 1	#Index to an effect block.
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 2	#Index to an effect block.
	.byte 211
	.byte 6	#New Instrument (6).
	.byte 1	#Index to an effect block.
	.byte 211
	.byte 4	#New Instrument (4).
	.byte 18	#Index to an effect block.
	.byte 211
	.byte 6	#New Instrument (6).
	.byte 3	#Index to an effect block.
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 2	#Index to an effect block.
	.byte 211
	.byte 3	#New Instrument (3).
	.byte 3	#Index to an effect block.
	.byte 211
	.byte 4	#New Instrument (4).
	.byte 4	#Index to an effect block.
	.byte 211
	.byte 3	#New Instrument (3).
	.byte 1	#Index to an effect block.
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 2	#Index to an effect block.
	.byte 211
	.byte 4	#New Instrument (4).
	.byte 3	#Index to an effect block.
	.byte 211
	.byte 5	#New Instrument (5).
	.byte 1	#Index to an effect block.
	.byte 211
	.byte 4	#New Instrument (4).
	.byte 4	#Index to an effect block.
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 2	#Index to an effect block.
	.byte 211
	.byte 3	#New Instrument (3).
	.byte 4	#Index to an effect block.
	.byte 211
	.byte 5	#New Instrument (5).
	.byte 1	#Index to an effect block.
	.byte 83
	.byte 12	#Index to an effect block.
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 2	#Index to an effect block.
	.byte 211
	.byte 3	#New Instrument (3).
	.byte 12	#Index to an effect block.
	.byte 211
	.byte 4	#New Instrument (4).
	.byte 3	#Index to an effect block.
	.byte 147
	.byte 6	#New Instrument (6).
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track3:
	.byte 255
	.byte 79	#Escape note (79).
	.byte 7	#New Instrument (7).
	.byte 13	#Index to an effect block.
	.byte 61, 6	#Waits for 7 lines.

	.byte 63
	.byte 77	#Escape note (77).
	.byte 61, 6	#Waits for 7 lines.

	.byte 63
	.byte 72	#Escape note (72).
	.byte 61, 6	#Waits for 7 lines.

	.byte 63
	.byte 76	#Escape note (76).
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track4:
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 8	#Index to an effect block.
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 255
	.byte 75	#Escape note (75).
	.byte 7	#New Instrument (7).
	.byte 15	#Index to an effect block.
	.byte 61, 6	#Waits for 7 lines.

	.byte 63
	.byte 71	#Escape note (71).
	.byte 61, 6	#Waits for 7 lines.

	.byte 63
	.byte 77	#Escape note (77).
	.byte 61, 6	#Waits for 7 lines.

	.byte 63
	.byte 79	#Escape note (79).
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track5:
	.byte 146
	.byte 8	#New Instrument (8).
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track6:
	.byte 222
	.byte 10	#New Instrument (10).
	.byte 8	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 30
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 30
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 128
	.byte 0	#New Instrument (0).
	.byte 61, 5	#Waits for 6 lines.

	.byte 146
	.byte 10	#New Instrument (10).
	.byte 30
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 30
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 30
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track7:
	.byte 210
	.byte 12	#New Instrument (12).
	.byte 8	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 128
	.byte 0	#New Instrument (0).
	.byte 61, 5	#Waits for 6 lines.

	.byte 210
	.byte 12	#New Instrument (12).
	.byte 19	#Index to an effect block.
	.byte 82
	.byte 2	#Index to an effect block.
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 18
	.byte 124	#No note, but effects.
	.byte 0	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track8:
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 8	#Index to an effect block.
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 19
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 163
	.byte 9	#New Instrument (9).
	.byte 99
	.byte 4	#Index to an effect block.
	.byte 99
	.byte 3	#Index to an effect block.
	.byte 99
	.byte 1	#Index to an effect block.
	.byte 99
	.byte 12	#Index to an effect block.
	.byte 99
	.byte 18	#Index to an effect block.
	.byte 99
	.byte 22	#Index to an effect block.
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 2	#Index to an effect block.
	.byte 19
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 19
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 19
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track9:
	.byte 144
	.byte 10	#New Instrument (10).
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 5	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track10:
	.byte 159
	.byte 9	#New Instrument (9).
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 147
	.byte 2	#New Instrument (2).
	.byte 60	#Waits for 1 line.

	.byte 159
	.byte 9	#New Instrument (9).
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track11:
	.byte 144
	.byte 12	#New Instrument (12).
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 5	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track12:
	.byte 142
	.byte 10	#New Instrument (10).
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 9	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 11
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track13:
	.byte 211
	.byte 2	#New Instrument (2).
	.byte 8	#Index to an effect block.
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 19
	.byte 223
	.byte 4	#New Instrument (4).
	.byte 1	#Index to an effect block.
	.byte 223
	.byte 6	#New Instrument (6).
	.byte 4	#Index to an effect block.
	.byte 223
	.byte 3	#New Instrument (3).
	.byte 3	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track14:
	.byte 142
	.byte 12	#New Instrument (12).
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 9	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 11
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track15:
	.byte 162
	.byte 14	#New Instrument (14).
	.byte 62 + 3 * 64	#Optimized wait for 5 lines.

	.byte 31
	.byte 61, 8	#Waits for 9 lines.

	.byte 153
	.byte 8	#New Instrument (8).
	.byte 62 + 3 * 64	#Optimized wait for 5 lines.

	.byte 22
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track16:
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 159
	.byte 9	#New Instrument (9).
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 147
	.byte 2	#New Instrument (2).
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 19
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 19
	.byte 62 + 0 * 64	#Optimized wait for 2 lines.

	.byte 19
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 159
	.byte 9	#New Instrument (9).
	.byte 62 + 1 * 64	#Optimized wait for 3 lines.

	.byte 147
	.byte 2	#New Instrument (2).
	.byte 60	#Waits for 1 line.

	.byte 159
	.byte 9	#New Instrument (9).
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 60	#Waits for 1 line.

	.byte 19
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track17:
	.byte 235
	.byte 13	#New Instrument (13).
	.byte 23	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 46
	.byte 60	#Waits for 1 line.

	.byte 50
	.byte 60	#Waits for 1 line.

	.byte 53
	.byte 60	#Waits for 1 line.

	.byte 52
	.byte 60	#Waits for 1 line.

	.byte 107
	.byte 1	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 46
	.byte 60	#Waits for 1 line.

	.byte 49
	.byte 60	#Waits for 1 line.

	.byte 53
	.byte 60	#Waits for 1 line.

	.byte 116
	.byte 3	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 46
	.byte 60	#Waits for 1 line.

	.byte 49
	.byte 60	#Waits for 1 line.

	.byte 52
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track18:
	.byte 150
	.byte 11	#New Instrument (11).
	.byte 62 + 3 * 64	#Optimized wait for 5 lines.

	.byte 19
	.byte 61, 8	#Waits for 9 lines.

	.byte 13
	.byte 62 + 3 * 64	#Optimized wait for 5 lines.

	.byte 10
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track19:
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 171
	.byte 16	#New Instrument (16).
	.byte 43
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 171
	.byte 16	#New Instrument (16).
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 159
	.byte 9	#New Instrument (9).
	.byte 171
	.byte 16	#New Instrument (16).
	.byte 43
	.byte 43
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 171
	.byte 17	#New Instrument (17).
	.byte 43
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 171
	.byte 17	#New Instrument (17).
	.byte 43
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 171
	.byte 17	#New Instrument (17).
	.byte 171
	.byte 18	#New Instrument (18).
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 171
	.byte 18	#New Instrument (18).
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 159
	.byte 9	#New Instrument (9).
	.byte 171
	.byte 18	#New Instrument (18).
	.byte 171
	.byte 19	#New Instrument (19).
	.byte 43
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 171
	.byte 19	#New Instrument (19).
	.byte 159
	.byte 9	#New Instrument (9).
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 171
	.byte 19	#New Instrument (19).
	.byte 147
	.byte 2	#New Instrument (2).
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track20:
	.byte 235
	.byte 15	#New Instrument (15).
	.byte 24	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 11	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 21	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 17	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 10	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 6	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 6	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 11	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 16	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 17	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 10	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 6	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 6	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 11	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 16	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 124	#No note, but effects.
	.byte 10	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track21:
	.byte 235
	.byte 7	#New Instrument (7).
	.byte 14	#Index to an effect block.
	.byte 60	#Waits for 1 line.

	.byte 46
	.byte 60	#Waits for 1 line.

	.byte 50
	.byte 60	#Waits for 1 line.

	.byte 53
	.byte 60	#Waits for 1 line.

	.byte 52
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 46
	.byte 60	#Waits for 1 line.

	.byte 49
	.byte 60	#Waits for 1 line.

	.byte 53
	.byte 60	#Waits for 1 line.

	.byte 52
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 43
	.byte 60	#Waits for 1 line.

	.byte 46
	.byte 60	#Waits for 1 line.

	.byte 49
	.byte 60	#Waits for 1 line.

	.byte 52
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track22:
	.byte 128
	.byte 0	#New Instrument (0).
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track23:
	.byte 247
	.byte 10	#New Instrument (10).
	.byte 20	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track24:
	.byte 214
	.byte 1	#New Instrument (1).
	.byte 8	#Index to an effect block.
	.byte 22
	.byte 23
	.byte 23
	.byte 25
	.byte 26
	.byte 19
	.byte 19
	.byte 19
	.byte 19
	.byte 19
	.byte 19
	.byte 23
	.byte 19
	.byte 26
	.byte 19
	.byte 25
	.byte 25
	.byte 25
	.byte 25
	.byte 27
	.byte 28
	.byte 22
	.byte 22
	.byte 22
	.byte 22
	.byte 22
	.byte 21
	.byte 20
	.byte 19
	.byte 18
	.byte 17
	.byte 61, 127	#Waits for 128 lines.


AHarmlessGrenade_Subsong0_Track25:
	.byte 255
	.byte 72	#Escape note (72).
	.byte 12	#New Instrument (12).
	.byte 7	#Index to an effect block.
	.byte 61, 127	#Waits for 128 lines.


#The speed tracks
AHarmlessGrenade_Subsong0_SpeedTrack0:
	.byte 255	#Wait for 128 lines.

#The event tracks
AHarmlessGrenade_Subsong0_EventTrack0:
	.byte 255	#Wait for 128 lines.

AHarmlessGrenade_Subsong0_DisarkByteRegionEnd0:
