# Sound Effects for song Sound effects, version 2.0, generated by Arkos Tracker 2.

# The sound effects, starting at 1.
        .word Soundeffects_Subsong_SoundEffect1 # Sound effect 1.
        .word Soundeffects_Subsong_SoundEffect2 # Sound effect 2.
        .word Soundeffects_Subsong_SoundEffect3 # Sound effect 3.
        .word Soundeffects_Subsong_SoundEffect4 # Sound effect 4.
        .word Soundeffects_Subsong_SoundEffect5 # Sound effect 5.

# Sound effect 1.
Soundeffects_Subsong_SoundEffect1:
        .byte 0         # Speed.
Soundeffects_Subsong_SoundEffect1_Loop:
        .byte 189       # Soft only. Volume: 15.
        .byte 1         # Noise: 1.
        .word 95        # Software period.

        .byte 189       # Soft only. Volume: 15.
        .byte 1         # Noise: 1.
        .word 99        # Software period.

        .byte 177       # Soft only. Volume: 12.
        .byte 1         # Noise: 1.
        .word 102       # Software period.

        .byte 173       # Soft only. Volume: 11.
        .byte 1         # Noise: 1.
        .word 106       # Software period.

        .byte 4         # End of the sound effect.

# Sound effect 2.
Soundeffects_Subsong_SoundEffect2:
        .byte 1         # Speed.
Soundeffects_Subsong_SoundEffect2_Loop:
        .byte 189       # Soft only. Volume: 15.
        .byte 1         # Noise: 1.
        .word 301       # Software period.

        .byte 189       # Soft only. Volume: 15.
        .byte 8         # Noise: 8.
        .word 319       # Software period.

        .byte 185       # Soft only. Volume: 14.
        .byte 2         # Noise: 2.
        .word 402       # Software period.

        .byte 181       # Soft only. Volume: 13.
        .byte 16        # Noise: 16.
        .word 213       # Software period.

        .byte 177       # Soft only. Volume: 12.
        .byte 2         # Noise: 2.
        .word 225       # Software period.

        .byte 173       # Soft only. Volume: 11.
        .byte 2         # Noise: 2.
        .word 239       # Software period.

        .byte 165       # Soft only. Volume: 9.
        .byte 16        # Noise: 16.
        .word 358       # Software period.

        .byte 157       # Soft only. Volume: 7.
        .byte 31        # Noise: 31.
        .word 119       # Software period.

        .byte 153       # Soft only. Volume: 6.
        .byte 7         # Noise: 7.
        .word 80        # Software period.

        .byte 4         # End of the sound effect.

# Sound effect 3.
Soundeffects_Subsong_SoundEffect3:
        .byte 1         # Speed.
Soundeffects_Subsong_SoundEffect3_Loop:
        .byte 189       # Soft only. Volume: 15.
        .byte 1         # Noise: 1.
        .word 119       # Software period.

        .byte 57        # Soft only. Volume: 14.
        .word 60        # Software period.

        .byte 181       # Soft only. Volume: 13.
        .byte 1         # Noise: 1.
        .word 95        # Software period.

        .byte 49        # Soft only. Volume: 12.
        .word 47        # Software period.

        .byte 185       # Soft only. Volume: 14.
        .byte 1         # Noise: 1.
        .word 80        # Software period.

        .byte 61        # Soft only. Volume: 15.
        .word 40        # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 15        # Hardware period.
        .word 478       # Software period.

        .byte 61        # Soft only. Volume: 15.
        .word 239       # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 15        # Hardware period.
        .word 478       # Software period.

        .byte 61        # Soft only. Volume: 15.
        .word 239       # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 15        # Hardware period.
        .word 478       # Software period.

        .byte 61        # Soft only. Volume: 15.
        .word 239       # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 30        # Hardware period.
        .word 956       # Software period.

        .byte 61        # Soft only. Volume: 15.
        .word 239       # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 30        # Hardware period.
        .word 956       # Software period.

        .byte 61        # Soft only. Volume: 15.
        .word 239       # Software period.

        .byte 4         # End of the sound effect.

# Sound effect 4.
Soundeffects_Subsong_SoundEffect4:
        .byte 1         # Speed.
Soundeffects_Subsong_SoundEffect4_Loop:
        .byte 189       # Soft only. Volume: 15.
        .byte 1         # Noise: 1.
        .word 119       # Software period.

        .byte 61        # Soft only. Volume: 15.
        .word 56        # Software period.

        .byte 189       # Soft only. Volume: 15.
        .byte 1         # Noise: 1.
        .word 106       # Software period.

        .byte 61        # Soft only. Volume: 15.
        .word 53        # Software period.

        .byte 61        # Soft only. Volume: 15.
        .word 100       # Software period.

        .byte 61        # Soft only. Volume: 15.
        .word 50        # Software period.

        .byte 4         # End of the sound effect.

# Sound effect 5.
Soundeffects_Subsong_SoundEffect5:
        .byte 1         # Speed.
Soundeffects_Subsong_SoundEffect5_Loop:
        .byte 3         # Soft and Hard. Env: 8.
        .word 2         # Hardware period.
        .word 27        # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 3         # Hardware period.
        .word 47        # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 2         # Hardware period.
        .word 30        # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 5         # Hardware period.
        .word 75        # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 3         # Hardware period.
        .word 47        # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 7         # Hardware period.
        .word 119       # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 5         # Hardware period.
        .word 75        # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 12        # Hardware period.
        .word 190       # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 7         # Hardware period.
        .word 119       # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 19        # Hardware period.
        .word 301       # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 12        # Hardware period.
        .word 190       # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 34        # Hardware period.
        .word 536       # Software period.

        .byte 3         # Soft and Hard. Env: 8.
        .word 50        # Hardware period.
        .word 804       # Software period.

        .byte 4         # End of the sound effect.

